GaloisInc/cryptol

- src/Cryptol/Symbolic/Prims.hs
Here is an example of the bug this aims to fix:
Cryptol> :prove \x y -> {a=x,b=y} == {b=y:Bit,a=x:Bit}
(\x y -> {a = x, b = y} ==
{b = y : Bit, a = x : Bit}) False True = False
> canonicalize records during comparison in :prove

- cryptol.cabal
By moving `build-depends` under the `if flag(server)` check. The diff
is a little hard to read, because I did not change the indentation of
the dependencies. Thanks @elliottt for the fix!
See comments on https://github.com/GaloisInc/cryptol/commit/0d61ed14c33aaa25845d016215c146184334d22c for context.
> Only require cryptol-server's build depends when it's being built.

- src/Cryptol/Parser/NoInclude.hs
Guesses the pre-processing from the file extension, as is done by parseModule.
> Fix for issue #258 (incude of literate file fails)

- cryptol-server/Main.hs
- cryptol.cabal
- cryptol/REPL/Haskeline.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/Utils/PP.hs
This notably adds a `MonadBaseControl` instance for the `REPL` monad so
that we can catch asynchronous exceptions in the middle of `REPL`
computations. Since this is a generalization of Haskeline's exception
support, that orphan instance for the console executable is now in terms
of this new instance.
> Improve handling of interrupts for non-Haskeline frontends

- cryptol.cabal
- src/Cryptol/Eval/Env.hs
- src/Cryptol/Eval/Value.hs
- src/Cryptol/ModuleSystem/Env.hs
- src/Cryptol/ModuleSystem/Interface.hs
- src/Cryptol/ModuleSystem/Monad.hs
- src/Cryptol/ModuleSystem/Name.hs
- src/Cryptol/ModuleSystem/NamingEnv.hs
- src/Cryptol/ModuleSystem/Renamer.hs
- src/Cryptol/Parser/AST.hs
- src/Cryptol/Parser/LexerUtils.hs
- src/Cryptol/Parser/NoInclude.hs
- src/Cryptol/Parser/NoPat.hs
- src/Cryptol/Parser/ParserUtils.hs
- src/Cryptol/Parser/Position.hs
- src/Cryptol/Prims/Syntax.hs
- src/Cryptol/TypeCheck/AST.hs
- src/Cryptol/TypeCheck/InferTypes.hs
- src/Cryptol/TypeCheck/Monad.hs
- src/Cryptol/Utils/PP.hs
deepseq-generics-0.2 stopped reexporting NFData from deepseq.
Patch imports it explicitly.
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
> tweak for deepseq-generics-0.2

- cryptol.cabal
Previously, `cabal sdist` would fail to include these fails in a tarball when uploaded to Hackage, causing the benchmarks to fail to run when obtained from there. Explicitly listing them in `extra-source-files` ensures `cabal sdist` grabs them.
Fixes #332.
> Put bench/data/*.cry in extra-source-files

- lib/Cryptol/Extras.cry
This adds the common `iterate` function to the `Cryptol::Extras` module.
> lib/extras: add iterate

- cryptol/Main.hs
- cryptol/REPL/Haskeline.hs
- cryptol/REPL/Logo.hs
This adds a `--color` command line option, which allows you to control how colors are output by the frontend. It has three settings: `none`, `always`, and `auto`.
This also adds a fix for the usage of `setTitle` in Cryptol, to set the terminal title. Previously this was always set no matter what, when the REPL was reloaded or a new module loaded, but this breaks inside Emacs, as it can't handle those values within the `ansi-terminal` mode, via `comint`. It can handle ANSI color escape codes, however.
Notably, while color can be controlled explicitly, the autodetection of whether to set the terminal title *cannot* be controlled explicitly. Mostly, I see no reason to support extra code for this. Also, while there may be cases like Emacs where color autodetection should be overridden, I …
> Fix up terminal title usage and color output

- src/Cryptol/Eval/Monad.hs
- src/Cryptol/Eval/Reference.lhs
- src/Cryptol/Prims/Eval.hs
- src/Cryptol/Symbolic/Prims.hs
Make values lazier with respect to when they produce divide-by-0
errors.  Divide-by-0 should now propigate in the same way that
user errors do.
In addition, fix a bug in the reference evaluator with respect to
divide-by-0 handling of pmod and pdiv.  Previously, the `polyDivMod`
function would raise a division by zero error, in contravariance
to the reference implementation invariant that errors may only
occur when forcing values at type `Bit`.
> Perform more careful handling of divide-by-0 conditions.

- src/Cryptol/TypeCheck/Solver/Numeric.hs
- src/Cryptol/TypeCheck/Type.hs
- src/Cryptol/TypeCheck/TypePat.hs
- tests/issues/issue212.icry.fails
- tests/issues/issue212.icry.stdout
Check for situations where a unification variable is involved in
a sum of terms not containing additional unification variables,
and replace it with a solution and an inequality.
`s1 = ?a + s2 ~~> (?a = s1 - s2, s1 >= s2)`
Fixes #212
> Add a rule to the numeric solver for "linear unifiers"

- cryptol.cabal
- src/Cryptol/Symbolic.hs
- src/Cryptol/Symbolic/Value.hs
SBV 8.0 is now on hackage, with several backwards compatibility breaking changes. You'll need this patch to compile cryptol against it.
> Make Cryptol compile with SBV 8.0

- cryptol.cabal
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/Symbolic.hs
@brianhuffman @atomb @yav 
SBV 8.1 is out on hackage, and I'm afraid it'll be a while before another one comes out. Hopefully, it doesn't have any glaring bugs!
This pull request contains changes to Cryptol so:
1. You can compile with SBV 8.1
2. It fixes the "elapsed time printing" bug: https://github.com/GaloisInc/cryptol/issues/572
3. It fixes the "sharing" bug triggered for the uses of `svChangeSign`: https://github.com/GaloisInc/cryptol/issues/566
4. It adds support for barrel-rotations so you can implement faster rotates, discussed here: https://github.com/GaloisInc/cryptol/issues/573
5. It adds a model-validator feature to Cryptol, piggy backing on the same SBV 8.1 feature, that can help with issue reported in ticket: https://github.com/GaloisInc/cryptol/issues/558
And hopefully it …
> Changes required to compile Cryptol with SBV 8.1; and model-validation support

- src/Cryptol/REPL/Command.hs
- src/Cryptol/Testing/Random.hs
- src/Cryptol/Utils/PP.hs
Here's a REPL command to dump generated tests instead of running them, so that they can be consumed by other tools.
I have a couple of questions, pre-merge:
1. The docs for this command are longer than the others due to describing its interaction with options. Should it be shortened, should they be lengthened, or is it OK?
2. Is there a CHANGELOG or NEWS file that I should update?
> Command to dump generated tests

- src/Cryptol/REPL/Command.hs
- src/Cryptol/Testing/Random.hs
Instead of panicking, :dumptests will now print the message
"The expression is not of a testable type" when used with an
inappropriately-typed expression. Also, Integer return values
are now supported.
Fixes #615.
> Make :dumptests check whether type is testable before starting.

- cryptol/REPL/Logo.hs
Added a helpful line to the startup message, specified by #617. Looks like:
```
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.7.1 (ede8c3f)
https://cryptol.net  :? for help
Loading module Cryptol
Cryptol>
```
> Add help hint to Cryptol REPL

- src/Cryptol/ModuleSystem/Renamer.hs
- tests/issues/issue614.cry
- tests/issues/issue614.icry
- tests/issues/issue614.icry.stdout
This does fixity resolution for types during renaming, with proper error reporting when conflicting fixities are encountered.
Fixes issue #614.
> Do renaming on types the same way we do renaming on expressions.

- tests/cryptol-test-runner.cabal
Assigns a valid license to the cryptol-test-runner (to match cryptol itself) and updates the maintainer.
> Update cryptol-test-runner maintainer and license

- cryptol.cabal
Apparently version 0.8 contains some breaking changes.
> Add cabal bounds to the `haskeline` package.

- src/Cryptol/Eval/Reference.lhs
- src/Cryptol/IR/FreeVars.hs
1. Cryptol can reference declarations in where clause sequentially so we need to remove the declarations from their body as well. 
2. Exporting evalExpr and evalDeclGroup so I can use them in code generation.
> Fix for freevars and adding some exports.

- lib/Cryptol.cry
- tests/issues/T146.icry.stdout
- tests/issues/issue290v2.icry.stdout
> Redefine prelude function `iterate` to preserve sharing.

- cryptol.cabal
- cryptol/REPL/Haskeline.hs
- src/Cryptol/REPL/Monad.hs
The version of haskeline was updated for GHC 8.10 (haskeline is one of the bundled libraries in the GHC distribution), and the newer version of haskeline contains some non-backwards-compatible changes that are addressed by this pull request.
More specifically, haskeline dropped its internal MonadExceptions module in favor of using the standard `exceptions` package (pull request 97 in haskeline) which necessitates the addition of some new class instances (and the removal of the MonadException instance) for GHC 8.10.
> Updates for haskeline 0.8 and use of exceptions package.

- src/Cryptol/Transform/Specialize.hs
- src/Cryptol/TypeCheck/Default.hs
- src/Cryptol/TypeCheck/Monad.hs
- src/Cryptol/TypeCheck/Sanity.hs
- src/Cryptol/TypeCheck/Solver/Improve.hs
- src/Cryptol/TypeCheck/Subst.hs
- src/Cryptol/TypeCheck/Type.hs
- src/Cryptol/TypeCheck/TypeOf.hs
- src/Cryptol/TypeCheck/Unify.hs
- tests/issues/issue723.cry
- tests/issues/issue723.icry
- tests/issues/issue723.icry.stdout
This patch adds/changes some functions in the `Cryptol.TypeCheck.Subst` module to make it harder to accidentally make `Subst` values that violate the datatype invariant (a situation that can lead to a `panic`).
Fixes #723.
> Enforce datatype invariants when creating `Subst` values

- .github/workflows/nightly.yml
In the latest nightly build, [here](https://github.com/GaloisInc/cryptol/actions/runs/116299915), windows failed. I had originally traced this back down to a problem with ghc 8.8 and windows not getting along super well but missed fixing this in the `nightly.yml` file. This corrects that omission.
> Serialize nightly windows builds

- src/Cryptol/Eval.hs
- src/Cryptol/Eval/Generic.hs
- src/Cryptol/Parser.y
- src/Cryptol/Parser/AST.hs
- src/Cryptol/Parser/LexerUtils.hs
- src/Cryptol/Parser/ParserUtils.hs
- src/Cryptol/Parser/Utils.hs
- src/Cryptol/TypeCheck/Infer.hs
This PR includes various changes to avoid using the unsafe, error-prone function `fromInteger` to convert from `Integer` to `Int` (see #637).
> Avoid using `fromInteger`.

- lib/Array.cry
- tests/regression/array.icry
- tests/regression/array.icry.stdout
Fixes this error:
```
Cryptol> :module Array
Parse error at Array:8:1,
unexpected: module
expected: a declaration
```
> Fix Array.cry comment.

- lib/Cryptol.cry
- src/Cryptol/Eval/Backend.hs
- src/Cryptol/Eval/Concrete.hs
- src/Cryptol/Eval/Generic.hs
- src/Cryptol/Eval/Reference.lhs
- src/Cryptol/Eval/SBV.hs
- src/Cryptol/Eval/What4.hs
- src/Cryptol/Prelude.hs
- tests/issues/T146.icry.stdout
- tests/issues/issue226.icry.stdout
- tests/issues/issue290v2.icry.stdout
- tests/issues/issue723.icry.stdout
The old `round` operation is renamed into `roundAway` to make its
semantics more obvious.
> Implement `roundToEven` and `roundAway`

- cryptol/Main.hs
- cryptol/REPL/Logo.hs
> Add a command-line option to disable unicode characters in the REPL logo

- .github/workflows/build.yml
Look at me, submitting a PR that touches less than 20 files. What a concept.
[A bug in GHC](https://gitlab.haskell.org/ghc/ghc/-/issues/17926) (more accurately, `process-1.6.8`) makes building with ghc 8.8.3 on windows inside a RAM constrained environment somewhat finicky. This also technically affects 8.10 as well, but it seems to be more reliable about things so far, so we'll see how that one goes.
If necessary, I'll go back to building the releases with 8.6.5 so that we can turn off windows+ghc 8.8.3 without making the yaml files super ugly.
> Disable builds on windows for which there's a memory leak

- src/Cryptol/TypeCheck/Error.hs
- src/Cryptol/TypeCheck/Infer.hs
- src/Cryptol/TypeCheck/Monad.hs
- src/Cryptol/TypeCheck/SimpType.hs
- src/Cryptol/TypeCheck/SimpleSolver.hs
- src/Cryptol/TypeCheck/Solve.hs
- src/Cryptol/TypeCheck/Solver/Numeric.hs
- src/Cryptol/TypeCheck/Type.hs
- tests/issues/issue101.icry.stdout
- tests/issues/issue582.icry.stdout
- tests/mono-binds/test04.icry.stdout
- tests/regression/float.icry.stdout
The error messages are better but still need a bit of work,
especially when there are malformed types, such as `0 - 1`
> Some improvement on issue #768.

- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
This PR accomplishes two things:
* Documents the arguments to `:set tc-debug` in-REPL (closes #560)
* Provides more details on how use the REPL `:help` command (closes #629)
To accomplish the latter, this PR adds a `cLongHelp` field to `CommandDescr` and prints it when `:help` is called with an argument.  This also lays the groundwork for the comment @brianhuffman made on #612 .
> Better document `:help` and `:set tc-debug`

- Dockerfile
This change downloads specific stable release versions of each supported SMT solver to the Dockerfile. In cases where a build was available(yices, cvc4, Mathsat), it is downloaded directly. In other cases, it is built from a specific source snapshot (boolector, abc). These versions could be changed if desired.
This allows easy access to Cryptol and all solvers in a single Docker container, which is useful since some common problems are not amenable to solution with Z3 alone.
As with the original Cryptol Dockerfile, this implementation uses Docker's staged build functionality both to keep the final size as small as possible and to modularize the build. If desired, this segment could be copied verbatim to the SAW Dockerfile to add additional solvers there as well.
Note that this Dockerfile …
> Add additional SMT solvers to Docker image.

- src/Cryptol/TypeCheck/Default.hs
- src/Cryptol/TypeCheck/Error.hs
- tests/mono-binds/test05.icry.stdout
messages when the calculated bound is 0.
> Suppress the `Must be at least` line of defaulting error

- src/Cryptol/Eval/Reference.lhs
- src/Cryptol/ModuleSystem.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/ModuleSystem/Monad.hs
- src/Cryptol/Parser/NoInclude.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/Symbolic/SBV.hs
- src/Cryptol/Symbolic/What4.hs
- src/Cryptol/Transform/Specialize.hs
This PR adds the ability for clients of Cryptol-the-library to provide their own means of accessing files on disk, as a sort of lightweight VFS. This will be used for caching multiple concurrent states in the SAW RPC interface.
> Parameterize module system over filesystem access

- .github/workflows/build.yml
The documentation around github.ref leaves a little to be desired, and I apparently wasn't reading it closely enough. This allows the release workflow to actually trigger on the release branches.
> Allow release branches to actually release

- .github/workflows/build.yml
- .github/workflows/nightly.yml
This enables docker builds for releases and nightlies. It also (*probably*) pushes them correctly to dockerhub.
> Enable docker builds for releases and nightlies

- src/Cryptol/Eval/Generic.hs
- src/Cryptol/Eval/Value.hs
- tests/issues/issue861.cry
- tests/issues/issue861.icry
- tests/issues/issue861.icry.stdout
Fixes #861
I'd like to add some tests and do some additional checking, but I think this fixes the issue.
Related, however: `:check` should probably fail when we encounter an error condition, the same way that `:prove` does.  Right now, I think it just accepts crashing test cases as passing.
> Check for negative integer indices when doing indexing-out-of-bounds checks

- cryptol.cabal
- src/Cryptol/Eval/Concrete.hs
- src/Cryptol/Eval/Monad.hs
- src/Cryptol/Eval/SBV.hs
- src/Cryptol/Eval/Value.hs
- src/Cryptol/Eval/What4.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/ModuleSystem/Monad.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/Symbolic/SBV.hs
- src/Cryptol/Symbolic/What4.hs
- src/Cryptol/Testing/Random.hs
With the addition of `parmap`, it became possible to observe race conditions in the thunk evaluation lifecycle.  This PR reworks the evaluation monad so that threads will properly block and wait if they attempt to force a thunk that is already under evaluation by a different thread and uses transactional variables to ensure proper synchronization.
> Fix race conditions in thunk evaluation

- src/Cryptol/Eval.hs
- src/Cryptol/Eval/Env.hs
Benchmarks using `examples/AES.cry` and `Primitive/Keyless/Hash/SHA1.cry` from the cryptol-examples repo show that using `IntMap` instead of `Map` for the value environment yields a speedup of about 7 or 8 percent, and a reduction in memory footprint of about 4 or 5 percent.
> Switch evaluation environment from Data.Map to Data.IntMap.

- src/Cryptol/ModuleSystem/Interface.hs
- src/Cryptol/Parser.y
- src/Cryptol/Parser/AST.hs
- src/Cryptol/Parser/NoPat.hs
- src/Cryptol/Parser/ParserUtils.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/TypeCheck/AST.hs
- src/Cryptol/TypeCheck/Depends.hs
- src/Cryptol/TypeCheck/Kind.hs
- src/Cryptol/TypeCheck/Type.hs
Use `Text` instead of `String` to represent docstrings. This reduces the memory footprint of loaded cryptol modules a bit.
> Docstring text

- .github/ci.sh
- .github/workflows/nightly.yml
- .gitmodules
- cabal.project
This adds the `argo` repository as a submodule, which in turn allows us to build the RPC API server `cryptol-remote-api` as part of the normal Cryptol build process. Ultimately, the code for that server will migrate into the Cryptol repository itself, and `argo` may eventually become a Hackage dependency.
> Include `cryptol-remote-api` in Cryptol builds

- src/Cryptol/Eval.hs
- src/Cryptol/Eval/Env.hs
- src/Cryptol/Eval/Monad.hs
- src/Cryptol/Eval/Reference.lhs
- src/Cryptol/Eval/Type.hs
- src/Cryptol/TypeCheck/Type.hs
Use `IntMap` for type environments instead of Data.Map.
Fixes #886
> Intmap types

- src/Cryptol/TypeCheck/Error.hs
- src/Cryptol/TypeCheck/Monad.hs
- src/Cryptol/TypeCheck/Subst.hs
- src/Cryptol/TypeCheck/Type.hs
- src/Cryptol/TypeCheck/TypeMap.hs
- src/Cryptol/Utils/Misc.hs
A few other constructor fields also needed to be made strict
to avoid space leaks.
Fixes #888.
> Make `apSubst` more strict to avoid a space leak.

- src/Cryptol/Eval/Backend.hs
- src/Cryptol/Eval/Concrete/Value.hs
- src/Cryptol/Eval/SBV.hs
- src/Cryptol/Eval/What4.hs
- src/Cryptol/Eval/What4/Float.hs
- src/Cryptol/Eval/What4/SFloat.hs
- src/Cryptol/Eval/What4/Value.hs
- src/Cryptol/Symbolic.hs
- src/Cryptol/Symbolic/SBV.hs
- src/Cryptol/Symbolic/What4.hs
Refactor some of the symbolic backend code.  This brings the What4 and SBV backends closer together in terms of structure. We also fix some bugs regarding the use of defining equations in the What4 backend, and give the SBV backend the same basic defining equation ability.
> Symbolic refactor

- src/Cryptol/REPL/Command.hs
- tests/regression/itreuse.icry
- tests/regression/itreuse.icry.stdout
so we can cache the value via it's thunk.  This prevents reevaluating
the term when the "it" variable is referenced later.
Fixes #881
> Bind an expression to the "it" variable _before_ evaluating it

- src/Cryptol/Eval/Reference.lhs
The C code generation I'm working on calls the reference evaluator, and relies on the `E` type being exposed so we can handle the error conditions.
> Exposes the E monad, which is needed for C code generation work.

- src/Cryptol/Parser/LexerUtils.hs
> Update the lexer to allow `'` characters in record selectors

- cryptol-remote-api/src/CryptolServer/Data/Expression.hs
- cryptol.cabal
- lib/Cryptol.cry
- lib/Cryptol/Reference.cry
- src/Cryptol/Eval.hs
- src/Cryptol/Eval/Concrete.hs
- src/Cryptol/Eval/Value.hs
- src/Cryptol/F2.hs
- src/Cryptol/ModuleSystem.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/Prelude.hs
- src/Cryptol/Symbolic/SBV.hs
- src/Cryptol/Symbolic/What4.hs
- src/Cryptol/Utils/Ident.hs
- tests/issues/T146.icry.stdout
- tests/issues/T820.icry.stdout
- tests/issues/issue290v2.icry.stdout
- tests/issues/issue723.icry.stdout
- tests/issues/issue910.icry.stdout
- tests/regression/f2polytest.cry
- tests/regression/f2polytest.icry
- tests/regression/f2polytest.icry.stdout
- tests/regression/instance.icry.stdout
- tests/regression/tc-errors.icry.stdout
Add new primitives for `pmult`, `pdiv` and `pmod`.  Currently, these are exposed in the prelude via new symbols named `fast_pmult`, `fast_pdiv` and `fast_pmod`.  The plan is to relocate the current in-Cryptol implementations to a reference implementation module and continue to use these definitions for the symbolic backends, along the lines suggested in #922. 
These still require additional testing, but seem to work correctly on a limited selection of tests.
> Fast F2 polynomial arithmetic

- cryptol.cabal
Fix for `cabal sdist` and `cabal install` following #923 .  The subdirectories of `lib` were not being included in the source distribution.
> Update cabal file to include all relevant files in the `lib` directory

- cryptol-remote-api/test-scripts/Foo.cry
Requires merge of https://github.com/GaloisInc/argo/pull/112 first and a fixing of submodule.
> chore: submodule bump, test type-level operators

- src/Cryptol/TypeCheck/Solve.hs
- tests/issues/issue877.cry
- tests/issues/issue877.icry
- tests/issues/issue877.icry.stdout
Add rules to default types at the command line for type variables not constrained by literal constraints.
> REPL defaulting

- src/Cryptol/ModuleSystem/InstantiateModule.hs
- src/Cryptol/TypeCheck.hs
- src/Cryptol/TypeCheck/Infer.hs
- tests/issues/Issue796.cry
- tests/issues/Issue796_Sig.cry
- tests/issues/Issue883.cry
- tests/issues/Issue883_A.cry
- tests/issues/Issue883_Impl.cry
- tests/issues/Issue883_Sig.cry
- tests/issues/issue796.icry
- tests/issues/issue796.icry.stdout
- tests/issues/issue883.icry
- tests/issues/issue883.icry.stdout
- tests/issues/issue883_A.icry
- tests/issues/issue883_A.icry.stdout
This fixes #796.
It also fixes the @bboston7's example on #883, but not the original
example in #883.   The issue there is that `asdf` function generates
a constraint only involving the module parameter.
Normally we don't try to solve constraint that don't mention a schema's
parameters, because they can always be solved "later", and hopefully with
more things instantiated.
The weird thing in this case is that the schema adds *local" constraint to
the module parameters, but we end up ignoring these.
> Bug fixes to the modules system.

- src/Cryptol/Backend/What4.hs
- tests/issues/issue958.icry
- tests/issues/issue958.icry.stdout
> Fix the bit-order convention for `extractWord` in the What4 backend

- cryptol-remote-api/cryptol-remote-api.cabal
- cryptol-remote-api/test-scripts/cryptol-api_test.py
- cryptol-remote-api/test-scripts/cryptol-tests.py
* Integrates Argo's support for HTTP (https://github.com/GaloisInc/argo/pull/101)
* Updates command-line arguments to use the subcommand style (inherited from the Argo update)
* Enables threading
> HTTP transport support in cryptol-remote-api

- src/Cryptol/Eval/Concrete.hs
- src/Cryptol/Eval/Generic.hs
- src/Cryptol/Eval/SBV.hs
- src/Cryptol/Eval/What4.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/Testing/Random.hs
Refactor testing code for `:check` and `:exhaust`.  This simplifies the interface to the testing code, and allows us to finally close #98.
> Check refactor

- lib/PrimeEC.cry
- src/Cryptol/Backend/What4.hs
- src/Cryptol/Eval/What4.hs
- src/Cryptol/PrimeEC.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/Symbolic/What4.hs
- tests/regression/twinmult.cry
- tests/regression/twinmult.icry
- tests/regression/twinmult.icry.stdout
Add support to the What4 provers for treating the SuiteB AES primitives
as uninterpreted functions.  This allows basic use of `:safe`, and
also allows one to prove basic facts using `:prove`, provided they
don't rely on any interesting properties of the AES primitives.
Proof counterexamples and `:sat` results, however, are very likely
to be spurious.
The SHA-2 and PrimeEC primitives are next to get the same treatment.
Eventually, we should probably make the symbolic behavior of these primitives configurable.
> Uninterpreted primitives

- docs/ProgrammingCryptol/Makefile
Two different Makefiles each copied it and used different file names.
Closes #969.
> Don't add an extra copy of Programming Cryptol

- cry
> cry: propagate command failure

- .github/Dockerfile-remote-api
Improve the cryptol-remote-api Dockerfile to bind to port 8080 and EXPOSE it. This makes the container play nicer when used as a service like in GitLab.
With this change you could use this as:
```.gitlab-ci.yml
services:
- galoisinc/cryptol-remote-api:nightly
```
Example:
```.gitlab-ci.yml
stages:
- ci
cryptol-example:
stage: ci
services:
- galoisinc/cryptol-remote-api:nightly
script:
- >-
curl -s -H 'Content-Type: application/json' -H 'Accept: application/json' -XPOST -d '{"jsonrpc":"2.0","id":1,"method":"load module","params":{"module name":"Cryptol","state":null}}' galoisinc-cryptol-remote-api:8080
```
> Make cryptol-remote-api Dockerfile default to 8080 and EXPOSE it

- cryptol-remote-api/src/CryptolServer/Data/Expression.hs
- cryptol-remote-api/src/CryptolServer/Data/Type.hs
- cryptol-remote-api/test-scripts/cryptol-tests.py
- cryptol-remote-api/test-scripts/test-data/M.cry
Now, serialized Cryptol expressions get to take type arguments.
RE https://github.com/GaloisInc/argo/issues/105
> cryptol-remote-api: Add type application form

- cryptol-remote-api/README.rst
This consists of a mix of README content migrated from the argo repo and fresh content that was missing here.
I'd appreciate one of the reviewers merging this PR if it gets approved, as I'm out for the next couple of weeks.
> Add README for cryptol-remote-api

- cryptol-remote-api/cryptol-eval-server/Main.hs
- cryptol-remote-api/src/CryptolServer.hs
- cryptol-remote-api/src/CryptolServer/Data/Expression.hs
- cryptol-remote-api/src/CryptolServer/EvalExpr.hs
- cryptol-remote-api/src/CryptolServer/Options.hs
- cryptol-remote-api/src/CryptolServer/Sat.hs
- src/Cryptol/Backend.hs
- src/Cryptol/Backend/Concrete.hs
- src/Cryptol/Backend/FloatHelpers.hs
- src/Cryptol/Backend/Monad.hs
- src/Cryptol/Backend/SBV.hs
- src/Cryptol/Backend/What4.hs
- src/Cryptol/Eval.hs
- src/Cryptol/Eval/Concrete.hs
- src/Cryptol/Eval/Env.hs
- src/Cryptol/Eval/Generic.hs
- src/Cryptol/Eval/Reference.lhs
- src/Cryptol/Eval/SBV.hs
- src/Cryptol/Eval/Value.hs
- src/Cryptol/Eval/What4.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/ModuleSystem/Monad.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/Symbolic.hs
- src/Cryptol/Symbolic/SBV.hs
- src/Cryptol/Symbolic/What4.hs
- src/Cryptol/Utils/PP.hs
Builds on PR #985 
This refactors how evaluation options are piped into primitives, and makes them work in a less surprising way.  Currently, this only affects the `trace` and `traceVal` functions. This change makes it pretty straightforward to have the symbolic and concrete evaluators work uniformly with the same implementation for `trace`.
> Refactor evopts

- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/Testing/Random.hs
- tests/issues/Issue639_C.cry
- tests/issues/Issue639_M.cry
- tests/issues/issue639.icry
- tests/issues/issue639.icry.stdout
Fixes issues with the bulk testing/proving commands `:prove`, `:check` etc. that occur when properties are loaded in some dependent module, but not currently in scope.
> Property fix

- src/Cryptol/REPL/Command.hs
This change exposes `qcExpr` and `TestReport` in `REPL.Command` so that clients can easily quickcheck terms.
> Expose `qcExpr` in REPL.Command

- .github/Dockerfile-remote-api
- .github/ci.sh
- Dockerfile
The regular update to point to a nightly build that still exists.
> Fix CVC4 version used in Docker builds

- src/Cryptol/Backend/FloatHelpers.hs
- tests/issues/issue1049.icry
- tests/issues/issue1049.icry.stdout
Previously, some subnormal values were being incorrectly encoded.
Fixes #1049
Waiting on some local testing to finish before merging, but I'm pretty confident about this fix.
> Fix the binary encoding of floating-point values.

- src/Cryptol/Symbolic/SBV.hs
- src/Cryptol/TypeCheck/Depends.hs
- src/Cryptol/TypeCheck/Infer.hs
- tests/issues/issue1040.cry
- tests/issues/issue1040.icry
- tests/issues/issue1040.icry.stdout
- tests/issues/issue1044.icry
- tests/issues/issue1044.icry.stdout
when parsing SBV counterexamples.
After parsing all the "input" values, there may be some left over
if we have used constructs (like prime field recip) that are
defined via uniquely specified variables.  We can simply ignore
these extra values.
> Relax the check that all values are consumed

- src/Cryptol/Testing/Random.hs
- tests/issues/issue1049.icry
- tests/issues/issue1049.icry.stdout
- tests/regression/FloatTests.cry
- tests/regression/float.icry
- tests/regression/float.icry.stdout
Implement `:exhaust` for floating point values, and improve the random generator to produce more representative samples.
> Float check

- .github/workflows/nightly.yml
- cryptol-remote-api/Dockerfile
- cryptol-remote-api/ghc-portability.patch
Builds cryptol-remote-api without eventfd and timerfd
> Init ghcr.io/galoisinc/cryptol-remote-api:nightly-portable

- cryptol-remote-api/Dockerfile
This is probably a better place for the remote cryptol to serve files from by default, right?
> change remote Dockerfile's cwd for server

- src/Cryptol/Parser.y
- src/Cryptol/Parser/ParserUtils.hs
- src/Cryptol/Parser/Position.hs
- src/Cryptol/TypeCheck/Error.hs
- src/Cryptol/TypeCheck/Kind.hs
- tests/issues/issue322.icry.stdout
- tests/issues/issue845.icry.stdout
- tests/issues/issue962.icry
- tests/issues/issue962.icry.stdout
- tests/issues/issue962a.cry
- tests/issues/issue962b.cry
- tests/regression/tc-errors.icry.stdout
Fix parsing/typechecking issues arising from explicit type applications occurring in unexpected places.
This change restricts some programs that were previously accepted, but were rather unusual, I think.  E.g.
```
f`{5}`{Integer}
```
Is a program that used to be accepted with the same meaning as
```
f`{5,Integer}
```
After this patch, the first program with an error indicating that type applications are only allowed on identifiers.
> Fix parse panic

- src/Cryptol/Symbolic.hs
- src/Cryptol/Symbolic/SBV.hs
- tests/issues/issue1093.icry
- tests/issues/issue1093.icry.stdout
> Make `freshVar` produce a VWord instead of a VSeq for type `[0]`.

- cryptol-remote-api/python/.gitignore
This is useful for ensuring that autogenerated `__pycache__` directories
resulting from running the tests do not pollute the `git` tree.
> Add Python-centric .gitignore file for cryptol-remote-api/python directory

- cryptol-remote-api/python/README.md
- cryptol-remote-api/python/cryptol/__init__.py
- cryptol-remote-api/python/poetry.lock
- cryptol-remote-api/python/pyproject.toml
- cryptol-remote-api/python/tests/cryptol/test_cryptol_api.py
- cryptol-remote-api/run_rpc_tests.sh
A handful of tweaks needed to make `cryptol-remote-api`'s Python code `mypy`-clean:
* `__del__` needs an explicit `-> None` return type.
* `BitVector` has no type annotations, so `type: ignore` it.
While I was in town, I:
* Made sure that running `mypy` is a part of CI.
* Added a `pyproject.toml` file for running Python-related commands with `poetry`, much like we have in `saw-remote-api`.
> Make cryptol-remote-api mypy-clean

- cryptol-remote-api/python/cryptol/bitvector.py
- cryptol-remote-api/python/poetry.lock
- cryptol-remote-api/python/pyproject.toml
- cryptol-remote-api/python/requirements.txt
- cryptol-remote-api/python/setup.py
This upgrades `mypy` to version `0.812`. This is primarily motivated by a need to work around python-poetry/poetry#3094, which currently happens if you try to include the SAW Python bindings in a `poetry` project as a `develop` dependency. For the most part, this is a matter of adjusting version bounds. In a handful of cases, we are able to remove `type: ignore` comments due to `mypy-0.8` being smarter than `mypy-0.7`.
> cryptol-remote-api: Upgrade to mypy-0.812

- src/Cryptol/Backend/FloatHelpers.hs
- tests/regression/float.icry.stdout
That mode has highly counterintuitive results.  Instad, use the `showFree`
mode, which produces results more accurate to the underlying
bit representation.  The `showFree` mode often produces unfortunate
trailing zeros in decimal representations, so we take some care
to trim those out.
Fixes #1089
> Don't use the `showFreeMin` floating-point printing mode

- cryptol-remote-api/cryptol-eval-server/Main.hs
- cryptol-remote-api/src/CryptolServer.hs
- cryptol-remote-api/src/CryptolServer/EvalExpr.hs
- cryptol-remote-api/src/CryptolServer/Sat.hs
- cryptol-remote-api/src/CryptolServer/TypeCheck.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/ModuleSystem/Env.hs
- src/Cryptol/ModuleSystem/Monad.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/TypeCheck/Monad.hs
Push solver instances higher, into the REPL monad or the SolverState.
Some remaining questions regarding the remote API server:
1. Will this cause problems with concurrent clients?
2. There doesn't seem to be any way to do cleanup actions when
the server is shut down, so the solver will not be shut down
gracefully.  Is this a problem?
> Persist solver, part 2

- tests/regression/instance.cry
- tests/regression/instance.icry
- tests/regression/instance.icry.stdout
Fixes #1144
Some of the corresponding instances from saw-core are a little too restrictive, we should update them.
> Update the instances regression test to include `LiteralLessThan`

- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
Generally, the CTRL^C will cause the solver to exit, so
this shuts down the current instance forces the REPL to
reopen a fresh instance the next time it is required.
Fixes #1157
> Reset the TC solver on CTRL^C

- README.md
Currently, the GitHub Actions README badge doesn't display properly:
After this patch, it now looks like:
> Use correct link for GitHub Actions README badge

- cryptol-remote-api/python/cryptol/__init__.py
- cryptol-remote-api/python/tests/cryptol/test_AES.py
- cryptol-remote-api/python/tests/cryptol/test_cryptol_api.py
- cryptol-remote-api/src/CryptolServer/Sat.hs
Add an equivalent to the REPL's `:safe` to the python API.
Addresses https://github.com/GaloisInc/cryptol/issues/1166
> feat(rpc): safe for python api

- src/Cryptol/ModuleSystem/NamingEnv.hs
> Don't panic on ambig, so that we have a chance to report the error

- src/Cryptol/F2.hs
Used with a modulus of degree `d`, the low `d` bits of the input can be copied directly to the output unchanged. This lets us skip the first `d` iterations of the main loop.
This change reduces the runtime of my 42,000-bit polynomial GCD function from just over 3 minutes to less than 2.
> Add a shortcut to speed up concrete evaluation of pmod.

- src/Cryptol/Backend/SeqMap.hs
- src/Cryptol/Backend/WordValue.hs
- tests/issues/issue1191.cry
- tests/issues/issue1191.icry
- tests/issues/issue1191.icry.stdout
> Fix for issue 1191

- cryptol-remote-api/python/tests/cryptol/test_SHA256.py
- cryptol-remote-api/src/CryptolServer/Data/Expression.hs
For example, when using the cryptol Python bindings `c.eval('[]')` returns `()` when it should return `[]`.
This change fixes the commented-out code in [this example](https://github.com/GaloisInc/cryptol/blob/master/cryptol-remote-api/python/tests/cryptol/test_SHA256.py#L20).
> rpc: Fix bug where an empty list is sent back from the server as Unit

- cryptol-remote-api/src/CryptolServer/Options.hs
- src/Cryptol/Eval/Value.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/TypeCheck/Monad.hs
- src/Cryptol/Utils/PP.hs
We're working on a cryptol-to-C compiler, and one way we've been validating that it's working right is to use the cryptol repl's `:dumptests` feature and a small C wrapper that treats them as golden tests. I'd like to keep the C wrapper's parser simple, and if records get printed with a predictable field order, that simplifies the parser a lot.
This pull request adds a feature for this: a new setting, `fieldOrder`/`field-order` in the REPL, which can be set to `canonical` or `display`, and which controls the pretty-printer for records. It defaults to `display` for backwards compatibility.
(Actually, I'm going to use a different branch than `master` for the C compiler, but I'd like to minimize drift between them if possible.)
> Add a field order option for the pretty-printer

- src/Cryptol/Backend/Monad.hs
This avoids expensive calls to `combineCallStacks` in the common case; the actual call stack values are only computed in the case where they need to be printed out.
This helps with #1201.
> Defer `CallStack` computations by representing them as data constructors.

- cryptol/Main.hs
- src/Cryptol/REPL/Monad.hs
This lets the user reset the module search path. It is a bit of a
blunt instrument as it resets the entire path.  Perhaps we should also
add the ability to add new paths to the front of the search order,
e.g. with a new `:prependpath` command?
Fixes #631
> Add a new 'path' option to the REPL

- cryptol-remote-api/cryptol-remote-api.cabal
- cryptol-remote-api/docs/Cryptol.rst
- cryptol-remote-api/python/cryptol/commands.py
- cryptol-remote-api/python/cryptol/solver.py
- cryptol-remote-api/python/tests/cryptol/test_cryptol_api.py
- cryptol-remote-api/src/CryptolServer/Sat.hs
- cryptol-remote-api/update_docs.sh
- src/Cryptol/REPL/Command.hs
Makes available both SBV and What4 based solver backends in the RPC server and Python client.
Addresses https://github.com/GaloisInc/argo/issues/173
> feat: support for all solver backends for cryptol server/client

- .github/ci.sh
- .github/workflows/ci.yml
- Dockerfile
We will need a better solution to getting CVC4 eventually, but unbreaking the builds, even temporarily, is high priority. And the right solution for CVC4, with the recent transition to CVC5, is somewhat tricky.
I believe the one test failure is an allowed failure and can be ignored for now.
> Attempt to fix CVC4 and Docker upload issues

- CHANGES.md
- cryptol-remote-api/cryptol-remote-api.cabal
- cryptol-remote-api/docs/Cryptol.rst
- cryptol-remote-api/src/CryptolServer/Sat.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/Symbolic.hs
- src/Cryptol/Symbolic/What4.hs
- tests/issues/issue072.icry.stdout
- tests/regression/allsat.cry
- tests/regression/allsat.icry
- tests/regression/allsat.icry.stdout
Reconfigure the What4 prover backends to use online/incremental mode instead of one-shot mode.
This significantly improve the performance of multi-SAT queries, partially addressing #1125.
> What4 online

- cryptol-remote-api/python/cryptol/connection.py
@kquick pointed out using `__del__` in this way to send a final HTTP request to reset the server could potentially cause problems and/or hangs in certain situations.
> fix: remove automatic reset from python client connection

- .github/workflows/ci.yml
This seems to break the CI, we need to investigate why
> Temporarily disable uploading artifacts for Windows.

- .github/workflows/ci.yml
This should move the creation of the portable Docker image to run only on nightly jobs, but that won't take effect until it's merged, due to how GitHub treats Actions.
> Improve CI for Windows and portable Docker container

- CHANGES.md
- src/Cryptol/ModuleSystem.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/ModuleSystem/Env.hs
- src/Cryptol/ModuleSystem/Exports.hs
- src/Cryptol/ModuleSystem/Renamer.hs
- src/Cryptol/Parser.y
- src/Cryptol/Parser/AST.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/TypeCheck.hs
- src/Cryptol/TypeCheck/Infer.hs
- src/Cryptol/TypeCheck/Monad.hs
- src/Cryptol/TypeCheck/Subst.hs
- tests/regression/repl-decls.icry
- tests/regression/repl-decls.icry.stdout
In particular, we can now define operators using `let` in the
same way that they can be inside modules and `where`.
In addition, we allow `type` and `type constraint` definitions
at the REPL, and `infix`, `infixl` and `infixr` declarations.
Becase it is an error for an infix declaration to be stated
without its corresponding declaration, we have added the ability
to enter multiple definitions at once, separated by `;`.  This
is also useful for definition mutually recursive definitions using
`let`.
> Add new declaration forms that can be parsed at the REPL

- cryptol-remote-api/src/CryptolServer.hs
- cryptol-remote-api/src/CryptolServer/LoadModule.hs
- src/Cryptol/TypeCheck/Solver/SMT.hs
Some difficult to reproduce bugs regarding the RPC server hanging
(https://github.com/GaloisInc/cryptol/issues/1250) seemed to be
related to the type checker solver (Z3) hanging after periods of
extended use. I.e., a module would load/error quickly normally,
but if preceded by enough prior solver/server activity, Z3
would consistently hang. To avoid this, we can simply reset the
solver and reload the type checker prelude when the server is asked
to load a file or module. This solves the Z3 hang issues in observed
cases and requires no additional forking (which we're trying to
minimize when possible).
> fix(rpc): reset TC solver on file/module load

- src/Cryptol/TypeCheck/SimpType.hs
max 1 (a ^ n) ~> a ^ n    (for a >= 1)
width (2 ^ n - 1) ~> n
Fixes #1291
> Add rewrite rules to simplify constraints due to `generate`.

- CHANGES.md
- lib/Cryptol.cry
- tests/issues/T146.icry.stdout
- tests/issues/issue1024.icry.stdout
- tests/issues/issue103.icry.stdout
- tests/issues/issue290v2.icry.stdout
- tests/issues/issue723.icry.stdout
- tests/regression/safety.icry.stdout
- tests/regression/tc-errors.icry.stdout
Here we provide an implementation for `sort` that is much more computationally efficient than the current one. For example, sorting 3000 Integers takes ~4 seconds where the current implementation takes over a minute.
There are two variations on merging two sorted lists to choose from. They seem similar in terms of runtime and time it takes to prove a property.
> A take at updating Cryptol's sort function from insertion sort to merge sort

- cryptol-remote-api/python/.gitignore
- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/cryptol/__init__.py
- cryptol-remote-api/python/cryptol/connection.py
- cryptol-remote-api/python/cryptol/cryptoltypes.py
- cryptol-remote-api/python/cryptol/custom_fstring.py
- cryptol-remote-api/python/cryptol/quoting.py
- cryptol-remote-api/python/cryptol/single_connection.py
- cryptol-remote-api/python/cryptol/synchronous.py
- cryptol-remote-api/python/tests/cryptol/test_quoting.py
This PR adds the function `cry_f` for quasiquoting cryptol using an f-string-like syntax. The example from GaloisInc/saw-script#1188 can now be written as:
```python
a = cry('g x')
b = cry_f('foo {a}')
```
This PR also adds `cry_eval_f` and `Connection.eval_f` which behave the same as composing `cry_eval` (or `Connection.eval`) with `cry_f`. See `tests/cryptol/test_quoting.py` for more examples.
Under the hood, `cry_f` uses Python's f-string parser and converts all of the bracketed arguments it is given into Cryptol syntax. This enables it to handle more complex expressions, like:
```python
cry_f('{ {"x": BV(size=8, value=1)} }')
cry_f('{{x = {BV(size=8, value=1)}}}')
```
both of which produce `cry('{x = 0x01}')`.
In making this PR I realized `cryptoltypes.py` needs a lot of cleaning up. …
> [RPC] f-string-like Cryptol quasiquotation

- cryptol-remote-api/cryptol-remote-api.cabal
- cryptol-remote-api/src/CryptolServer/AesonCompat.hs
- cryptol-remote-api/src/CryptolServer/Check.hs
- cryptol-remote-api/src/CryptolServer/Data/Expression.hs
- cryptol-remote-api/src/CryptolServer/Data/Type.hs
- cryptol-remote-api/src/CryptolServer/Exceptions.hs
- cryptol-remote-api/src/CryptolServer/Options.hs
This introduces some CPP, unfortunately, but this probably necessary to
continue allowing `cryptol-remote-api` to be buildable with old versions of
`aeson` until the ecosystem catches up with `aeson-2.0.*`.
> `cryptol-remote-api`: Allow building with `aeson-2.0.*`

- lib/Cryptol.cry
- lib/Cryptol/Reference.cry
- src/Cryptol/Eval/Generic.hs
- tests/issues/T146.icry.stdout
- tests/issues/issue1024.icry.stdout
- tests/issues/issue103.icry.stdout
- tests/issues/issue226.icry.stdout
- tests/issues/issue290v2.icry.stdout
- tests/issues/issue723.icry.stdout
- tests/regression/reference.cry
- tests/regression/reference.icry
- tests/regression/reference.icry.stdout
- tests/regression/safety.icry.stdout
- tests/regression/tc-errors.icry.stdout
This PR changes `scanl` to a primitive instead of a defined value in the Prelude.  In addition, a few other definitions in the Prelude were reimplemented to use `foldl` or `scanl` instead of being directly recursive.
These changes are primarily intended to support the Cryptol->Coq extraction use case in SAW.  That extraction currently has no way to translate recursive Cryptol programs, so it is useful to avoid them for basic functionality exposed via the Prelude.  With this PR the `sortBy` function is the only remaining recursive definition in the Prelude.
> Primitive scanl

- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/cryptol/bitvector.py
- cryptol-remote-api/python/cryptol/connection.py
- cryptol-remote-api/python/cryptol/cryptoltypes.py
Currently, `cryptoltypes.py` has the functions `to_cryptol`, `CryptolType.from_python`, and `CryptolType.convert`, all of which do approximately the same thing. Only the first is used in any current code in this repo or in saw-script, so this PR removes the latter two.
Currently, `__to_cryptol__` has a `CryptolType` parameter that does nothing, and `to_cryptol` has a `CryptolType` parameter that only matters in the following two cases:
```python
to_cryptol(x, Bitvector(Num(w))) == to_cryptol(BV(w, x)) # if x is an int
to_cryptol(x, Bitvector(Num(w))) == to_cryptol(BV.from_bytes(x, size=w)) # if x is a bytearray or bytes
```
Otherwise every Python value has a unique `CryptolType`, so the parameter is unused. These `CryptolType` parameters are never actually used in any current code in this …
> [RPC] Clean up `to_cryptol` interface in cryptoltypes.py

- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/cryptol/cryptoltypes.py
- cryptol-remote-api/python/cryptol/opaque.py
- cryptol-remote-api/python/cryptol/single_connection.py
- cryptol-remote-api/python/cryptol/synchronous.py
- cryptol-remote-api/python/pyproject.toml
- cryptol-remote-api/python/tests/cryptol/test-files/Types.cry
- cryptol-remote-api/python/tests/cryptol/test_basics.py
- cryptol-remote-api/python/tests/cryptol/test_types.py
This PR finishes cleaning up `cryptoltypes.py`, specifically:
- Finishes adding classes for all of the currently implemented Cryptol props (see [Cryptol.TypeCheck.TCon](https://github.com/GaloisInc/cryptol/blob/08cd609c4c58ebb5a4cd22ad053d8255ce8d1fc5/src/Cryptol/TypeCheck/TCon.hs#L200) and [CryptolServer.Data.Type](https://github.com/GaloisInc/cryptol/blob/08cd609c4c58ebb5a4cd22ad053d8255ce8d1fc5/cryptol-remote-api/src/CryptolServer/Data/Type.hs#L131))
- Adds class for `lengthFromTo` type operator
- Adds type annotations for all instance variables
- Finishes implementing `__str__` methods for all Cryptol types
- Uses `@dataclass` everywhere possible to avoid writing `__repr__` and `__eq__` methods
- Adds more docstrings
- Adds comments delineating sections
> [RPC] Finish cleaning cryptoltypes.py

- src/Cryptol/ModuleSystem/Base.hs
- tests/modsys/T1330.icry
- tests/modsys/T1330.icry.stdout
- tests/modsys/T1330/include.cry
- tests/modsys/T1330/main.cry
- tests/modsys/T1330/modA.cry
We have to do that, so that we can see included imports, and thus load
the correct dependencies for a module.
This fixes #1330
> Call `removeIncludes` very early---it is now part of parsing.

- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/pyproject.toml
This is intended to be what is committed to PyPI for the 2.12.4 release. After the release we'll bump again to the dev version 2.12.5.
> python client 2.12.4 PyPI release

- cabal.GHC-8.10.7.config
- cabal.GHC-8.8.4.config
- cabal.GHC-9.0.2.config
- cryptol.cabal
Among other things, `what4-1.3` includes [a bugfix](https://github.com/GaloisInc/what4/pull/148) that allows `what4` to correctly invoke modern versions of Boolector.
> Update `what4` dependency to `1.3`

- .github/workflows/ci.yml
- .gitpod.Dockerfile
- Dockerfile
- README.md
- cryptol-remote-api/Dockerfile
- cryptol-remote-api/ghc-portability.patch
This converts the `cryptol-remote-api` Dockerfiles to use GHC 8.10.7 instead of GHC 8.10.3, now that we have switched over to using 8.10.7 in the CI. This also updates `cryptol-remote-api`'s `ghc.portability` patch to use the 8.10.7 branch of GHC.
Fixes #1347.
> Fix the nightly `cryptol-remote-api` Docker builds

- .github/ci.sh
- .github/workflows/ci.yml
* Always sign binary artifacts, not just for releases. Fixes #1355.
* Trigger full releases after `git tag --push`. Fixes #1351.
* Use modern GPG keys. Fixes #1354.
> CI: Improve signing and tag workflows

- .github/wix.ps1
- .gitignore
- win32/cryptol.wxs
Previously, we would include every file in the current `cryptol` checkout in `cryptol.msi`, which would result in horribly bloated installer files. We now only include those files under the `dist` directory (created by `.github/ci.sh bundle_files`), which curates only those files we want to include in a binary distribution.
While I was in town, I modified the conventioned used in `win32/cryptol.wxs` so that we no longer need to reference `dist`, which does not show up in `.tar.gz`-based bindists.
Fixes #977.
> Only include bindist-related files in `cryptol.msi`

- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
Addresses #1345 
The problem: due to nondeterminism in the SMT solver, using `:check` on a property with numeric constraints can sometimes find and sometimes not find concrete instances for some numeric type variables. If the instance is not found, then the user is presented with the error message `Cannot evaluate polymorphic value.` which is misleading because, in fact, another run of `:check` might find an instance and to testing just fine.
In `Cryptol.REPL.Monad`, this PR introduces a new constructor to `REPLException`,
```
data REPLException =
...
| InstantiationsNotFound Schema
...
```
which is very similar to `EvalPolyError`, which is the misleading exception raised in #1345. The exception `InstantiationsNotFound` is only thrown when the user `:check`s a property, and …
> Better error message for when type variable instances are not found for :checking

- CHANGES.md
- src/Cryptol/Eval/What4.hs
- tests/issues/issue1359.icry
- tests/issues/issue1359.icry.stdout
In the case where the index is a symbolic `Integer` and the sequence is of length `n`, the What4 backend mistakenly chose `n` to be the largest possible index. This corrects it to instead be `n - 1`.
Fixes #1359.
> Fix off-by-one error in What4 implementation of `(@)`

- src/Cryptol/ModuleSystem/Renamer.hs
- src/Cryptol/ModuleSystem/Renamer/Error.hs
- src/Cryptol/Parser.y
- src/Cryptol/Parser/AST.hs
- src/Cryptol/Parser/Names.hs
- src/Cryptol/Parser/NoPat.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/TypeCheck/Infer.hs
- tests/issues/issue1322.icry
- tests/issues/issue1322.icry.stdout
- tests/regression/float.icry
- tests/regression/float.icry.stdout
Fixes #1322. Note that this is a breaking change for the unary `-` operator around higher precedence operators like `^^`, i.e. `-x^^2` now parses as `-(x^^2)` instead of `(-x)^^2`.
> Add fixities for prefix operators

- cryptol-remote-api/src/CryptolServer/Sat.hs
We should try to match Cryptol's default settings when invoking the remote API, but the `pcVerbose` value (`True`) didn't match the defaults. Changing this to `False` should fix #1378. There is a separate question of whether remote API users should be able to change this default, but for the time being, let's at least be consistent between Cryptol's settings and the remote API's settings.
> `cryptol-remote-api`: Don't use verbose SBV settings

- .github/workflows/ci.yml
- README.md
GitHub is deprecating (and eventually removing) its macOS 10.15 runners. See actions/virtual-environments#5583. Let's upgrade to a newer version in the CI. This proves relatively straightforward—the only other change required is to upgrade to a newer version of `what4-solvers`.
> CI: Use macOS 12

- lib/Array.cry
- tests/regression/array.icry.stdout
Currently, this primitive (like the other Array primitives) has
no computational interpretation, and is only used for stating
specifications that are used in SAW. As such, there are no changes to
the interpreter.
> Add a primitive for `arrayEq`

- .github/workflows/ci.yml
- src/Cryptol/Backend/FFI.hs
- src/Cryptol/Eval/FFI.hs
- src/Cryptol/ModuleSystem/Base.hs
- tests/ffi/ffi-reload.icry.stdout.darwin
- tests/ffi/ffi-runtime-errors.icry.stdout.darwin
- tests/ffi/test-ffi.icry.stdout.darwin
Also refactored some of the loading code to allow this to work nicely.
Fixes #1399.
> Print message in REPL when loading dynamic library for FFI

- .github/workflows/ci.yml
The GPG signing step requires access to repository secrets that (apparently) aren't visible to forks. Let's just not sign build artifacts on forks to avoid this issue.
This mirrors a corresponding change made to `saw-script`'s CI in GaloisInc/saw-script@eedcba1126f7c501ae443ee3fb5b8b07358acbe1 and GaloisInc/saw-script@ac082b0dd95b966a006a26de6e6564b2ffe523e3.
> CI: Don't sign build artifacts on forks

- src/Cryptol/ModuleSystem/Monad.hs
- tests/issues/issue1253.icry
- tests/issues/issue1253.icry.stdout
- tests/issues/issue1253.icry.stdout.mingw32
- tests/issues/issue1253a.cry
- tests/issues/issue1253b.cry
> Improve error message for ModuleNameMismatch error and add regression test.

- CHANGES.md
- cryptol.cabal
- src/Cryptol/Backend/FloatHelpers.hs
- src/Cryptol/Benchmark.hs
- src/Cryptol/Eval/Type.hs
- src/Cryptol/ModuleSystem.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- src/Cryptol/TypeCheck/FFI.hs
- src/Cryptol/Utils/Benchmark.hs
- src/Cryptol/Utils/Types.hs
- tests/issues/issue1415.icry
- tests/issues/issue1415.icry.stdout
Adds a `:time` command in the REPL for measuring the evaluation time of an expression. Uses [criterion-measurement](https://hackage.haskell.org/package/criterion-measurement) to do measurements.
The analysis that we do is very crude compared to what the full `criterion` package does (we basically just calculate the average times), but `criterion` pulls in much more dependencies so I don't think it's worth adding it.
Closes #1415.
> Add `:time` command

- .github/workflows/ci.yml
This should avoid nasty linker errors as observed in https://gitlab.haskell.org/ghc/ghc/-/issues/21111 until the upstream tools can be fixed.
> CI: Work around GHC installation issues on Windows

- CHANGES.md
- src/Cryptol/Parser/Unlit.hs
- tests/issues/issue1441_a.icry
- tests/issues/issue1441_a.icry.stdout
- tests/issues/issue1441_a.rst
- tests/issues/issue1441_b.icry
- tests/issues/issue1441_b.icry.stdout
- tests/issues/issue1441_b.rst
This implements supports for literate Cryptol with RST, see #1441
> Add support for literat Cryptol with RST

- .github/workflows/ci.yml
PR #1403 accidentally removed our build coverage for an older Ubuntu LTS configuration. This patch adds in back and ensures that we don't accidentally run the tests on this configuration.
> Include one Ubuntu 20.04 configuration

- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/TypeCheck/Sanity.hs
> Pretty printing for Core Lint errors

- src/Cryptol/Parser/Lexer.x
- src/Cryptol/Parser/Token.hs
- syntax-highlight/cryptol.vim
Adds a syntax highlighter for vim.   Also fixes a couple of weird things in the lexer.
Fixes #1462
> Vim syntax highlight

- cryptol-remote-api/python/GettingStarted.md
- cryptol-remote-api/python/README.md
Just an example of how to get started with the Python API
> Add an example on how to get started with the Python API

- CHANGES.md
- cryptol-remote-api/docs/Cryptol.rst
- cryptol-remote-api/python/cryptol/commands.py
- cryptol-remote-api/python/cryptol/connection.py
- cryptol-remote-api/python/cryptol/file_deps.py
- cryptol-remote-api/python/cryptol/single_connection.py
- cryptol-remote-api/python/cryptol/synchronous.py
- cryptol-remote-api/python/poetry.lock
- cryptol-remote-api/python/tests/cryptol/test_filedeps.py
- cryptol-remote-api/src/CryptolServer/FileDeps.hs
- src/Cryptol/Backend/FFI.hs
- src/Cryptol/ModuleSystem.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/REPL/Command.hs
Hopefully this should be faster as we just
parse the module and expand the includes.
We do not rename, typecheck, or evaluate anything.
> Module dependencies without loading

- src/Cryptol/Symbolic/What4.hs
This passes the value of `smtFile` to each call to `startSolverProcess` in the online `what4` backend, thereby fixing #1475. After this patch, the test case in #1475 now produces an `.smt2` file, as expected.
> Teach online `what4` backend about smtFile option

- .github/workflows/ci.yml
- cryptol-remote-api/python/poetry.lock
- cryptol-remote-api/python/pyproject.toml
- cryptol-remote-api/run_rpc_tests.sh
This patch:
* Bumps the `mypy` lower bounds to avoid incurring a dependency on `typed-ast`, which is being EOL'd soon. See python/typed_ast#179.
* Bumps the `argo` lower bounds to bring in the changes from GaloisInc/argo#195, which makes corresponding changes on the `argo` side.
Fixes #1491.
> Python: Bump `argo-client`, `mypy` versions

- cryptol-remote-api/CHANGELOG.md
- cryptol-remote-api/docs/Cryptol.rst
- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/cryptol/commands.py
- cryptol-remote-api/python/cryptol/connection.py
- cryptol-remote-api/python/cryptol/cryptoltypes.py
- cryptol-remote-api/python/cryptol/single_connection.py
- cryptol-remote-api/python/cryptol/synchronous.py
- cryptol-remote-api/python/tests/cryptol/test-files/Names.cry
- cryptol-remote-api/python/tests/cryptol/test_names.py
- cryptol-remote-api/src/CryptolServer/Data/Type.hs
- cryptol-remote-api/src/CryptolServer/Names.hs
As touched upon in #1492, currently the remote API does not provide as much information about names as the `browse` command does in the REPL. This PR expands the result of the `visible names` method (i.e. `names()` in the Python API) to include:
- all the additional information provided by the `browse` command (i.e. what module the name is from, whether or not it is a parameter, and whether or it not it is a property), as well as
- fixity information (i.e. whether or not the name is an infix operator, and if so its associativity and precedence level).
This PR also adds the `property_names` and `parameter_names` functions to the Python API, which return only those names which are properties or parameters, respectively.
Finally, this PR also fixes a bug where `names()` would sometimes hang …
> Add more info to `names()` in Python API

- .github/workflows/ci.yml
The version we were previously using (1.1.6) is affected by this bug, causing invocations of Poetry to fail:
https://github.com/ionrock/cachecontrol/issues/292
> CI: Upgrade Poetry and Python version

- cryptol-remote-api/python/pyproject.toml
This is motivated by a desire to switch away from `setuptools`, which has some unfortunate interactions with static analysis tools.
This also bumps the `argo` submodule to bring in the changes from https://github.com/GaloisInc/argo/pull/197, which applies similar changes.
> Python: Use poetry.core.masonry.api as build-backend

- cryptol.cabal
- src/Cryptol/Symbolic/SBV.hs
`sbv-10.0` brings in two changes to the SBV internals that affect Cryptol.
1. `sbv-10.0` removes the `generateSMTBenchmark` function in favor of two separate `generateSMTBenchmarkSat` and `generateSMTBenchmarkProof` functions.
2. `sbv-10.0` removes the `allSatHasPrefixExistentials` field of `AllSatResult`.
We now use the appropriate CPP to make Cryptol compile before and after these changes.
Fixes #1513.
> Support building with `sbv-10.*`

- .github/gen_html_context.py
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- CHANGES.md
- docs/RefMan/_templates/versions.html
- docs/index.html
Updates Github CI process to publish multiple versions of the documentation to the online documentation (github-pages) site.  Originally, only master documentation was deployed.  This change means that there are alternate versions of the documentation available (via a selector on the documentation page) for every PR and every tagged version (for which documentation is available, starting with v2.12.0).
> Enable Github CI build of documentation for all tags and PRs.

- .github/gen_html_context.py
- docs/RefMan/_templates/versions.html
This ensures that the versions and pull-requests presented in the online document selection list are in sorted order to make it easier to find the desired version of the documents.
> Add sorting to version/PR on generated documents index.

- cryptol-remote-api/test.Dockerfile
This really ought to have been done at the same time as #1493/#1519, but this was overlooked due to CI-related oversights.
Without these changes, the `cryptol-remote-api` Docker image fails to build. (This was something I noticed when preparing the 3.0.0 release.) Once this lands, I will push these to the `release-3.0.0` branch as well.
> `test.Dockerfile`: Sync Python, Poetry versions with CI

- cryptol-remote-api/check_docs.sh
- cryptol-remote-api/run_rpc_tests.sh
- cryptol-remote-api/test_docker.sh
This is the same as #1525 , but that one was on my fork that I was using to test the online doc generations, and I deleted the fork but forgot to merge 1525.
> cryptol-remote-api script shebang fixes

- cryptol-remote-api/python/cryptol/bitvector.py
- cryptol-remote-api/python/cryptol/quoting.py
- cryptol-remote-api/python/tests/cryptol/test_quoting.py
This PR updates `to_cryptol_str` to correctly sanitize strings. For example, if `s = '" \ \n'`, then `cry_f('{s}')` now correctly gives `'"\\" \\\\ \\n"'` instead of the unescaped `'"" \\ \n"'`.
> Sanitize strings in `to_cryptol_str` in quoting.py

- LICENSE
- LICENSE.rtf
- README.md
- cryptol-remote-api/python/pyproject.toml
* Mention version 3, not 2, of Cryptol. This fixes #1542
* Modernize the copyright years slightly
* Mention significant contributions from @qsctr, @Riib11, and @m-yac
> Modernize the `README` slightly

- cryptol-remote-api/CHANGELOG.md
- cryptol-remote-api/cryptol-remote-api.cabal
- cryptol-remote-api/cryptol-remote-api/Main.hs
- cryptol-remote-api/docs/Cryptol.rst
- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/cryptol/commands.py
- cryptol-remote-api/python/cryptol/connection.py
- cryptol-remote-api/python/cryptol/single_connection.py
- cryptol-remote-api/python/cryptol/synchronous.py
- cryptol-remote-api/python/pyproject.toml
- cryptol-remote-api/src/CryptolServer/Version.hs
- src/Cryptol/Version.hs
This PR adds a `version` command to the `cryptol-remote-api` and its Python interface. For example:
```python
>>> connection.version()
CryptolVersionInfo(
rpc_version='3.0.1.99',
version='3.0.0.99',
commit_hash='8c811b06a435f5009e8b75b36ecc8fc220e4d6bd',
commit_branch='version-python-cmd',
commit_dirty=True,
ffi_enabled=True)
```
See the [docs for the command in `Version.hs`](https://github.com/GaloisInc/cryptol/blob/3d69f6dc7fe1a00235e3794eb9a26bb011e9bafe/cryptol-remote-api/src/CryptolServer/Version.hs#L41) or the [docstring of `CryptolVersionInfo` in the Python API](https://github.com/GaloisInc/cryptol/blob/3d69f6dc7fe1a00235e3794eb9a26bb011e9bafe/cryptol-remote-api/python/cryptol/synchronous.py#L86) for descriptions of these fields.
Resolves #1544
> Add `version` command to cryptol-remote-api

- .github/workflows/ci.yml
- Dockerfile
- README.md
- cryptol-remote-api/Dockerfile
This includes the following changes:
* The bindist URLs now include the OS architecture, I have tweaked the parts of CI that downloads bindists accordingly.
* This snapshot includes `cvc5-1.0.5`, which has fixed a bug that was responsible for #1548. As such, this fixes #1548.
> CI: Bump what4-solvers snapshot to 20230711

- docs/RefMan/FFI.rst
This is a disclaimer that while you _can_ use impure functions in the Cryptol FFI, we make no guarantees about the precise behavior of the side effects that they functions may perform.
Fixes #1554.
> RefMan: document that the FFI expects pure functions

- src/Cryptol/TypeCheck/Subst.hs
Fixes #1569.
Not really sure how to test this since the `Type` field is not really used within Cryptol itself. GaloisInc/saw-script#1923 does seem to be fixed by this change though.
> Apply `apSubst` to `Type` field of `EPropGuards` in `TVars` instance for `Expr`

- cryptol-remote-api/src/CryptolServer/FileDeps.hs
- src/Cryptol/Backend/FFI.hs
- src/Cryptol/Eval.hs
- src/Cryptol/ModuleSystem/Base.hs
- src/Cryptol/ModuleSystem/Env.hs
- src/Cryptol/REPL/Command.hs
Make the `:file-deps` REPL command and the `file_deps` remote API call always return the path of a foreign dependency (shared library) when it __should__ exist (i.e. if there are `foreign` declarations in the module), instead of only if it currently exists. Furthermore, for each foreign dependency return a pair of a string and a boolean, representing the file path and whether or not the file actually currently exists. (In Python the pair is represented as a length-2 list.)
This addresses one part of #1574.
> Always show foreign dependencies in `file-deps`, and whether or not they exist on disk

- src/Cryptol/Backend/SeqMap.hs
* Make the code more thread safe
* Do a bounds check in the GC closure
Not sure if the 2nd is needed, or if we have an assumption that `lookupSeqMap` will only be called with in bounds values---this is something we should investigate and document.
> Changes that hopefully fix #1552.

- cryptol-remote-api/run_rpc_tests.sh
- cryptol-remote-api/test_docker.sh
This causes `poetry` to regenerate the `poetry.lock` file with newer versions of dependencies, which defeats the point of checking in the lock file in the first place.
This mirrors a similar change applied to SAW's CI in https://github.com/GaloisInc/saw-script/commit/67a25a81c4f154fd791188494d739274c7f1a236. The use of `poetry update` isn't actively causing problems with Cryptol's CI yet, but better to be safe than sorry.
> CI: Don't run `poetry update`

- src/Cryptol/TypeCheck/Module.hs
- src/Cryptol/TypeCheck/ModuleInstance.hs
- tests/issues/issue1590.cry
- tests/issues/issue1590.icry
- tests/issues/issue1590.icry.stdout
If a functor contains both a newtype and a type synonym referring to the newtype, then during instantiation we must apply the instantiation map to the types in the functor, so that the type synonym now refers to the instantiated newtype instead. Previously, we only applied type substitutions to the types in the functor, which would replace type variables with concrete types defined in the functor arguments, but would not replace any actual names.
Confusingly, the code referred to the instantiation map as "value substitutions" even though it can contain names in the type namespace. The "type substitutions" and "value substitutions" are better thought of as "`TVar -> Type` mappings" and "`Name -> Name` mappings". I have renamed them to better reflect this.
Fixes #1590.
> Apply functor instantiation map to types

- .github/workflows/ci.yml
- Dockerfile
- cryptol-remote-api/Dockerfile
Two CI fixes:
Fixes https://github.com/GaloisInc/cryptol/issues/1598.
Fixes https://github.com/GaloisInc/cryptol/issues/1599.
> CI fixes for #1598, #1599

- .github/ci.sh
- .github/workflows/ci.yml
- Dockerfile
- README.md
- cryptol-remote-api/Dockerfile
- src/Cryptol/Backend/Arch.hs
Fixes https://github.com/GaloisInc/cryptol/issues/1061.
> CI: Build and test both x86-64 and AArch64 macOS

- docs/ProgrammingCryptol/crashCourse/CrashCourse.tex
Fix some typos I noticed in the Programming Cryptol book.
- p-1 bits in an IEEE float refers to the significand, not the mantissa, at least according to the latest preferred terminology, which aims to keep the word "mantissa" for the full mantissa including the units bit;
- reciprocal rather than reciprocol;
- the example in 1.23 had the wrong module declarations; also insert a separator word between the verbatim blocks so they can be told apart.
Closes #1630.
> Fix some typos I noticed in the Programming Cryptol book.

- src/Cryptol/TypeCheck/Infer.hs
- src/Cryptol/TypeCheck/Sanity.hs
- tests/constraint-guards/type-sig-constraint.cry
- tests/constraint-guards/type-sig-constraint.icry
- tests/constraint-guards/type-sig-constraint.icry.stdout
Previously, `checkPropGuardCase` would not consider type signature constraints when determining how many proof applications to generate, which ultimately led to the issues observed in https://github.com/GaloisInc/saw-script/issues/2043. This is relatively easy to fix by ensuring that we pass these constraints as an additional argument to `checkPropGuardCase`.
This bug would have been caught if `coreLint` supported numeric constraint guards (#1647), so I have implemented `coreLint` support in a separate commit. As such, this PR fixes #1647.
It is difficult to fully validate that this fix works without SAW, but I have checked in a smoke test that checks if the guards in a numeric constraint guard definition have the expected number of proof applications.
> Fix typechecking of constraint guards with type signature constraints

- .github/workflows/ci.yml
- cryptol-remote-api/python/README.md
- cryptol-remote-api/python/cryptol/__init__.py
- cryptol-remote-api/python/cryptol/connection.py
- cryptol-remote-api/python/mypy.ini
- cryptol-remote-api/python/poetry.lock
- cryptol-remote-api/python/pyproject.toml
- cryptol-remote-api/python/tests/cryptol/test_basics.py
- cryptol-remote-api/python/tests/cryptol/test_cryptol_api.py
- cryptol-remote-api/python/tests/cryptol/test_low_level_ops.py
- cryptol-remote-api/python/tests/cryptol_eval/test_basics.py
- cryptol-remote-api/test.Dockerfile
Fix #1653 Fix #1645
This PR also bumps cryptol-remote-api to python 3.12. Added a note in the cryptol-remote-api readme for supported python versions.
> Update cryptol-remote-api to Python 3.12

- .github/workflows/ci.yml
- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/LICENSE
- cryptol-remote-api/python/mypy.ini
- cryptol-remote-api/python/poetry.lock
- cryptol-remote-api/python/pyproject.toml
Preparatory work for bumping cryptol-remote-api to version 3.1.1 for python 3.12 support
> Bump cryptol-remote-api to 3.1.1

- .github/workflows/ci.yml
Doing so is completely unnecessary, as we never actually need to build any Haskell code in these jobs (rather, we invoke pre-built executables instead).
Fixes #1668.
> CI: Don't download GHC in test jobs

- src/Cryptol/Eval/Reference.lhs
- tests/issues/issue1663.icry
- tests/issues/issue1663.icry.stdout
This synchronizes the implementation of `roundAway` in the reference evaluator with the implementation of `Cryptol.Backend.FloatHelpers.floatToInteger`, which expects `NearAway` rather than `Away`.
Fixes #1663.
> Fix `roundAway` implementation in reference evaluator

- .github/workflows/ci.yml
- cry
Previously, we attempted to scrub out `git` commits from release binaries using a `sed` invocation in the `cry` script, but as was observed in #1353, this ended up scrubbing out `git` commits on all builds, not just release ones. We have decided that we should just include `git` commits on all builds, so we can fix the issue by removing the buggy use of `sed`.
Unfortunately, `cabal`'s recompilation logic is not smart enough to always rebuild `GitRev.hs` on every new commit, even though it should. For this reason, we make the `./cry build` command temporarily dirty the `GitRev.hs` file so that it is forcibly rebuilt, then revert the change to `GitRev.hs` and rebuild. It's rather heavy-handed, but it works.
Fixes #1353.
> Always embed `git` commit into `--version` output

- .gitignore
- dev_setup.sh
Partially addresses #1673 
This adds a `dev_setup.sh` script to install dependencies for macos 14. 
- I noted the places where I think things are different for macos 12
- Some of this transfers to ubuntu; I'd expect changes in the gmp (different package manager) and what4 (different what4 solvers URL) installation 
Some other questions for reviewers:
- Normally I would put this in `scripts/` but there isn't any such directory here. Is there a more appropriate place to keep it, or is in the root directory fine?
> add dev_setup script for macOS 14 

- cryptol-remote-api/CHANGELOG.md
- cryptol-remote-api/docs/Errors.rst
- cryptol-remote-api/python/tests/cryptol/test_cryptol_api.py
- cryptol-remote-api/src/CryptolServer.hs
- cryptol-remote-api/src/CryptolServer/Check.hs
- cryptol-remote-api/src/CryptolServer/EvalExpr.hs
- cryptol-remote-api/src/CryptolServer/Exceptions.hs
- cryptol-remote-api/src/CryptolServer/Sat.hs
- src/Cryptol/ModuleSystem/Env.hs
- src/Cryptol/REPL/Monad.hs
The `check`, `prove or satisfy`, and `evaluate expression` commands now check if the type and schema of the supplied expression is valid, which can prevent panics that would arise from evaluating invalid expressions (e.g., ones that depend on definitions in parameterized modules). We do so by defining a `validEvalContext` function (inspired by a function of the same name in the Cryptol REPL) and using it where appropriate.
I discovered that there was an unused error code (see the `evalInParamMod` function) in the remote API for this exact scenario, so I have repurposed the error code for this kind of situation. I've also expanded its payload to include both type parameters and definitions from the parameterized module, much like how the Cryptol REPL's `EvalInParamMod` exception currently …
> `cryptol-remote-api`: Check for valid evaluation contexts

- src/Cryptol/ModuleSystem/Renamer/ImplicitImports.hs
- tests/issues/issue_1691_2.cry
- tests/issues/issue_1691_2.icry
- tests/issues/issue_1691_2.icry.stdout
The previous fix for #1691 only worked for 1-level of nesting.  This should fix it to work with all nesting.
> Make fixes for 1691 work with more nested modules.

- src/Cryptol/PrimeEC.hs
- src/GHC/Num/Compat.hs
- tests/issues/issue1675/issue1675.icry
- tests/issues/issue1675/issue1675.icry.stdout
Closes #1675 
This seems to be the root cause bug, but I think there are some other improvements @marsella had in mind as well that we should go ahead and get in.
> Issue#1675

- docs/RefMan/BasicSyntax.rst
- src/Cryptol/Parser/ParserUtils.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- tests/docstrings/T01.cry
- tests/docstrings/T02.cry
- tests/docstrings/T02.icry.stdout
- tests/docstrings/T03.icry.stdout
- tests/docstrings/T04.cry
- tests/docstrings/T04.icry.stdout
* Handle more prefix-stripping cases for docstrings
* Catch REPL exceptions when checking docstrings
* Process unlabeled docstring codeblocks in :check-docstrings
> Improve :check-docstrings

- src/Cryptol/TypeCheck/SimpType.hs
- src/Cryptol/TypeCheck/Solver/Numeric.hs
- tests/issues/issue1489/issue1489.cry
- tests/issues/issue1489/issue1489.icry
- tests/issues/issue1489/issue1489.icry.stdout
> Enhance TypeChecker with exponent rules

- src/Cryptol/REPL/Command.hs
> Don't report an error on unclosed, skipped code fence

- cryptol-remote-api/src/CryptolServer/CheckDocstrings.hs
- src/Cryptol/REPL/Command.hs
- tests/docstrings/T09.cry
- tests/docstrings/T09.icry
- tests/docstrings/T09.icry.stdout
> Gracefully skip docstrings on top-level functors

- src/Cryptol/TypeCheck/Infer.hs
- src/Cryptol/TypeCheck/Type.hs
This defines a `tIsNominal :: Type -> Maybe (NominalType, [Type])` function. There is one spot in `Cryptol.TypeCheck.Infer` where this can more neatly replace a manual pattern match on `TNominal`, so I went ahead and did this as well.
Fixes #1732.
> Define `tIsNominal` and use it

- cryptol-remote-api/src/CryptolServer/CheckDocstrings.hs
- src/Cryptol/REPL/Command.hs
- tests/docstrings/T11.cry
- tests/docstrings/T11.icry
- tests/docstrings/T11.icry.stdout
We can't currently check docstrings on interfaces or (uninstantiated) functors. This change ensures we gracefully handle docstring-checking being called on these kinds of modules.
While I'd like to give docstrings on interfaces a better story we need to work through what that story should be. This PR allows us to gracefully check all the .cry files in a project without having to know which ones are regular modules and which are interfaces and which are functors.
> Gracefully skip checking docstrings on interface modules

- src/Cryptol/TypeCheck/SimpType.hs
This PR fixes issue #1741, adding an extra simplification rule to the type checker.
> Simplify `inf - x` to `inf`

- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- tests/docstrings/T10.cry
- tests/docstrings/T10.icry
- tests/docstrings/T10.icry.stdout
- tests/issues/issue639.icry
- tests/issues/issue639.icry.stdout
- tests/suiteb/ECDSAKeyPair.icry
- tests/suiteb/ECDSAKeyPair.icry.stdout
- tests/suiteb/ECDSASigGen.icry
- tests/suiteb/ECDSASigGen.icry.stdout
- tests/suiteb/ECDSASigVerify.icry
- tests/suiteb/ECDSASigVerify.icry.stdout
This change aligns :check and friends with :check-docstrings. It ensures that these command check exactly the properties defined in the focused module and its locally defined submodules and any locally instantiated functors. This makes it more suitable for use while developing a module and for including in a module docstring.
> Limit :check to return only locally defined properties

- CHANGES.md
- cryptol-remote-api/src/CryptolServer/Data/Expression.hs
- src/Cryptol/Backend.hs
- src/Cryptol/Backend/Concrete.hs
- src/Cryptol/Backend/SBV.hs
- src/Cryptol/Backend/What4.hs
- src/Cryptol/Backend/WordValue.hs
- src/Cryptol/Eval.hs
- src/Cryptol/Eval/Concrete.hs
- src/Cryptol/Eval/Generic.hs
- src/Cryptol/Eval/SBV.hs
- src/Cryptol/Eval/Value.hs
- src/Cryptol/Eval/What4.hs
- src/Cryptol/Symbolic.hs
- src/Cryptol/Testing/Random.hs
Fixes #1740.  We can do this because the values (WordVal) already has its width, so we don't need to store it again.
> Remove bitvectors width from the value tag.

- cryptol-remote-api/python/CHANGELOG.md
- cryptol-remote-api/python/poetry.lock
- cryptol-remote-api/python/pyproject.toml
This updates the `cryptol` Python bindings to require the use of `argo-client-0.0.13` or later, bringing in the performance improvements from https://github.com/GaloisInc/argo/pull/216.
> Python: Require argo-client >=0.0.13

- CHANGES.md
- src/Cryptol/Eval/Generic.hs
- tests/issues/issue1749.cry
- tests/issues/issue1749.icry
- tests/issues/issue1749.icry.stdout
Previously, `splitV` would assume that if you were splitting a value `val` into something of type `[inf][each]`, then `val` must be a stream of type of `[inf * each]` (i.e., of type `[inf]`). This is not true in the corner case where `each` equals `0`, however. In that case, `val` is of type `[0]`, which is a word, not a stream. As such, we need to ensure that we do not call `fromSeq` on `val`, which crashes if `val` is not a stream or sequence.
Fixes https://github.com/GaloisInc/cryptol/issues/1749.
> Fix `splitV` when splitting empty sequence to type `[inf][0]`

- .github/check_book_update.sh
- .github/workflows/book.yml
- CONTRIBUTING.md
- docs/README.md
Follow up to #1748.
This adds a small CI job that will shout if you either
- update the ProgrammingCryptol PDF without changing the source code
- update the book source code without changing the PDF
@sauclovian-g Do you want this requirement to be documented in a README somewhere? Or maybe `CONTRIBUTING.md`?
> ci: add a check for the cryptol book pdf

- src/Cryptol/REPL/Command.hs
- tests/docstrings/T02.cry
- tests/docstrings/T02.icry.stdout
Additionally this allows empty doctest lines to be skipped without error
> Allow doctests to span multiple lines with a trailing \ like the REPL already supports

- cryptol-remote-api/python/tests/cryptol/test_modules.py
- cryptol-remote-api/src/CryptolServer/Modules.hs
> Correctly detect top-level parameterized modules in modules() API call

- .github/workflows/docs.yml
The doc generation run as part of CI attempts to build and deploy a version of the docs for each PR (which allows inspection of doc updates for a PR before it lands).  The docs build is done for the expected marge result (`merge_commit_sha`) of the PR, but if the PR has a merge conflict with the main branch, then the value for this field will be `null`, and thus this CI script will fail.
This change modifies the doc generation CI process to skip PR's that are in this state.
> Fix doc-gen CI to not fail on the existsence of a non-mergeable PR.

- .github/workflows/ci.yml
- Dockerfile
- README.md
- cryptol-remote-api/Dockerfile
- dev/dev_setup.sh
GitHub Actions is removing support for `macos-12` (see https://github.com/actions/runner-images/issues/10721), so this switches Cryptol's CI from `macos-12` to `macos-13` in order to support an x86-64 version of macOS. This also updates the associated documentation in the `README` and the `dev/dev_setup.sh` script accordingly.
> CI: Switch from `macos-12` to `macos-13`

- CHANGES.md
- src/Cryptol/IR/FreeVars.hs
Rather than computing the free variables of a `NominalType` definition, we only include the name of the `NominalType` itself as a free variable.
Fixes #1773.
> Fix `freeVars` calculation for `TNominal`

- lib/CryptolTC.z3
- src/Cryptol/TypeCheck/Solver/SMT.hs
- src/Cryptol/TypeCheck/TypePat.hs
Fixes https://github.com/GaloisInc/cryptol/issues/1777.
> Add `prime` to `isNumeric`, define `cryPrime` SMT-LIB function 

- docs/RefMan/conf.py
If `SOURCE_DATE_EPOCH` is set (which seems to be the case in the CI runner), then there's undocumented Sphinx adjustment of the date in the copyright string.  Avoid this by using a syntax that Sphinx will not recognize and change.
See https://github.com/sphinx-doc/sphinx/blob/74ec2204795481402322e75752547571a553cc4e/sphinx/config.py#L721 and https://github.com/sphinx-doc/sphinx/blob/74ec2204795481402322e75752547571a553cc4e/sphinx/config.py#L765-L766
Fixes #1575
> Modify the copyright to avoid sphinx auto-correction based on SOURCE_DATE_EPOCH

- .github/workflows/ci.yml
- .github/workflows/docs.yml
I discovered recently after updating a fork I'd had sitting around that its periodic CI runs on master were failing.
Apparently it isn't possible to have scheduled runs that are skipped in forks (see https://github.com/orgs/community/discussions/16109 for an open/ignored feature request) but it is at least possible to have them not break.
> Check the repository owner in CI tasks

- examples/ChaChaPolyCryptolIETF.md
- examples/OptionUtils.cry
- tests/examples/allexamples.icry.stdout
This copies over changes made to the upstream `cryptol-specs` version of the `ChaChaPolyCryptolIETF` spec, up to and including a change to make the `AEAD_CHACHA20_POLY1305_DECRYPT` function return an `Option` (as done in GaloisInc/cryptol-specs#240). This is in pursuit of the eventual goal of purging uses of the `(a, Bit)` Cryptol anti-pattern in favor of returning `Option` types, as described in GaloisInc/cryptol-specs#239.)
This checks off one box in GaloisInc/cryptol-specs#239.
> `ChaChaPolyCryptolIETF`: Return an `Option` in `AEAD_CHACHA20_POLY1305_DECRYPT`

- CHANGES.md
- src/Cryptol/TypeCheck/SimpType.hs
- tests/modsys/T1799.icry
- tests/modsys/T1799.icry.stdout
- tests/modsys/T1799/B.cry
- tests/modsys/T1799/Y.cry
- tests/modsys/T1799/Z.cry
Previously, `Cryptol.TypeCheck.SimpType.tExp` would attempt to simplify `a ^^ (x ^^ y)` to `a ^^ (x * y)` at the type level, which was blatantly wrong. I have changed this to a similar (but actually valid) rule that simplified `(a ^^ x) ^^ y` to `a ^^ (x * y)`. (This law is normally stated with the condition that `a != 0`, but this law even works in Cryptol when `a == 0` due to the fact that `0 ^^ 0 == 1` in Cryptol.)
Fixes https://github.com/GaloisInc/cryptol/issues/1799.
> Fix simplification rule for nested type-level exponentiation

- src/Cryptol/TypeCheck/AST.hs
- src/Cryptol/TypeCheck/Infer.hs
- src/Cryptol/TypeCheck/ModuleBacktickInstance.hs
- src/Cryptol/TypeCheck/Subst.hs
This allows us to simplify away trivially satisfied type-case in a single place. In particular this helps later compiler passes that work on specialized instances of polymorphic functions.
> Implement a smart constructor for EPropGuard

- .github/workflows/ci.yml
- CHANGES.md
- Dockerfile
- README.md
- cabal.GHC-9.4.8.config
- cabal.GHC-9.6.5.config
- cabal.GHC-9.8.2.config
- cryptol-remote-api/Dockerfile
- dev/dev_setup.sh
- src/Cryptol/Symbolic/What4.hs
- tests/issues/issue_1807.icry
- tests/issues/issue_1807.icry.stdout
> check if what4 adapter is present before setting timeout

- CHANGES.md
- src/Cryptol/Symbolic/SBV.hs
- tests/issues/issue_1808.icry
- tests/issues/issue_1808.icry.stdout
fixes #1808
* ~Yices still does not work due to unexpected behavior after a timeout is triggered (see: https://github.com/LeventErkok/sbv/issues/735)~ Workaround using deadman timer
* the special cases for CVC4/5 are addressed in the 11.1.5 release for SBV (which is not compatible with cryptol as it requires GHC 9.8)
> add special cases to handle setting timeouts for SBV-based solvers

- CHANGES.md
- src/Cryptol/TypeCheck/Infer.hs
- src/Cryptol/TypeCheck/Solve.hs
- tests/issues/issue1796.cry
- tests/issues/issue1796.icry
- tests/issues/issue1796.icry.stdout
fixes #1796 
this comes at the cost of increasing the time to
fail if the guards are truly non-exhaustive
> improve exhaustiveness check by attempting each guard as the consequent

- cryptol-remote-api/test_docker.sh
Unfortunately, this test case appears to cause various permission-related headaches (for reasons that are difficult to reproduce outside of GitHub Actions), and what's more, it seems to cause later tests to fail (perhaps due to the presence of a `.cryproject` file?). See #1823 for more details.
For the sake of getting the CI to work again, I am opting to just disable this test case when running the tests via Docker.
> Skip `test_project.py` when running in Docker

- src/Cryptol/TypeCheck/SimpType.hs
- src/Cryptol/TypeCheck/Solver/Numeric.hs
- src/Cryptol/Utils/Patterns.hs
- tests/issues/issue_1812.cry
- tests/issues/issue_1812.icry.stdout
this allows for the subtraction cancellation rule
to still apply after some exponent simplification
steps have already occurred
fixes #1812
> type simplification: improve subtraction cancellation with exponents

- .github/workflows/ci.yml
- Dockerfile
- README.md
- cryptol-remote-api/Dockerfile
- dev/dev_setup.sh
- dev/ubuntu24.04.Dockerfile
GitHub Actions is removing its Ubuntu 20.04 runners soon (https://github.com/actions/runner-images/issues/11101), so this patch removes CI support for Ubuntu 20.04 and makes Ubuntu 24.04 the latest supported Ubuntu version.
> CI: Support Ubuntu 24.04, drop 20.04 support

- Dockerfile
- cryptol-remote-api/Dockerfile
A stopgap measure intended to allow the Docker images to be useful pending a resolution to https://github.com/coder/coder/issues/17316.
Fixes #1840.
> Dockerfiles: Revert from Ubuntu 24.04 to 22.04

- docs/RefMan/REPLCommands.rst
- docs/RefMan/RefMan.rst
Added documentation as requested in #612
> Added documentation for REPL commands and :set-able options to reference manual

- src/Cryptol/Parser/AST.hs
- src/Cryptol/TypeCheck/Type.hs
- src/Cryptol/Utils/PP.hs
> Tweaks to line breaking in pretty printer.

- tests/ffi/c-calling-convention/ffi-type-errors.icry.stdout
- tests/issues/issue410.icry.stdout
The output for these tests are now slightly different due to the recently merged changed from https://github.com/GaloisInc/cryptol/pull/1292. These changes are benign, so let's accept them.
Fixes #1845.
> Test suite: Accept new output for `ffi-type-errors` and `issue410`

- CHANGES.md
- rust/cry-ffi/Cargo.toml
- rust/cry-ffi/LICENSE
Add entries about the new `abstract` calling convention to the changelog. Also add a `LICENSE` file to `cry-ffi`.
> Post-#1739 improvements to `cry-ffi`

- CHANGES.md
- cryptol/Main.hs
- src/Cryptol/REPL/Command.hs
- src/Cryptol/REPL/Monad.hs
- tests/docstrings/T13.cry
- tests/docstrings/T13.icry
- tests/docstrings/T13.icry.stdout
- tests/docstrings/T13.saw
- tests/docstrings/T14.cry
- tests/docstrings/T14.icry
- tests/docstrings/T14.icry.stdout
- tests/docstrings/T14.saw
- tests/docstrings/T15.cry
- tests/docstrings/T15.icry
- tests/docstrings/T15.icry.stdout
- tests/docstrings/mocksaw.sh
The command succeeds when `saw` returns 0. Saw output is suppressed because `saw` adds timestamps and absolute paths to all output.
Saw is launched directly, so there is no concern about shell commands escaping the notebook.
Fixes #1835
> Add :saw notebook command

- CHANGES.md
- cryptol.cabal
- docs/RefMan/BasicSyntax.rst
- src/Cryptol/REPL/Command.hs
- src/Cryptol/TypeCheck/AST.hs
- src/Cryptol/TypeCheck/Docstrings.hs
- tests/docstrings/T05.icry.stdout
- tests/docstrings/T10.icry.stdout
Closes #1842.
This works by adding `Text` of the form:
````md
```
:exhaust p
```
````
To the list of docstrings extracted from a module's `Decl`s, when `p` is a `Bit`-typed declaration that has the `property` `Pragma`.
I wasn't set up to run every test in the regression suite (particularly those requiring CVC4/CVC5/Bitwuzla/Yices); I've marked this as a draft for now, and will use CI to determine which (if any) additional golden/`.stdout` files I need to update.
> Generate `:exhaust` for simple properties.

- cryptol-remote-api/CHANGELOG.md
- cryptol-remote-api/cryptol-eval-server/Main.hs
- cryptol-remote-api/cryptol-remote-api.cabal
- cryptol-remote-api/cryptol-remote-api/Main.hs
- src/Cryptol/Version.hs
This bumps the `argo` submodule to bring in the changes from https://github.com/GaloisInc/argo/pull/220 and uses them to define `--version`/`-v` command-line options for the `cryptol-remote-api` and `cryptol-eval-server` executables, which behave much like they do in the `cryptol` executable.
Fixes #1815.
> Add `--version`/`-v` option to `cryptol-remote-api` and `cryptol-eval-server`

- Dockerfile
Fixes #1849 (for good this time).
> Dockerfile: Pass `--env-ext=.env` to `test-runner`

- CHANGES.md
- src/Cryptol/Parser.y
- src/Cryptol/Parser/Layout.hs
- tests/enum/BasicEnums.cry
- tests/enum/BasicEnums.icry
- tests/enum/BasicEnums.icry.stdout
This change removes an unnecessary shift/reduce error in the parser and removes previously unreachable grammar productions.
> Allow `;` between case branches

- src/Cryptol/Eval/FFI.hs
- src/Cryptol/Eval/FFI/Abstract.hs
- src/Cryptol/Eval/FFI/Abstract/Call.hsc
- src/Cryptol/Eval/FFI/C.hs
Being able to turn off the FFI is super-handy for being able to load cryptol in ghci and Haskell-language-server.
Obviously it should build with the feature turned off (if we're going to keep the feature). We might want an additional feature that *specifically* disabled the foreign exports just for when we're developing anything that's not the FFI itself.
This PR just gets things building again. We might want to solve some of the problems differently than implemented here.
> Get library building with FFI disabled

- rust/cry-ffi/src/lib.rs
The rust FFI doesn't correctly call `set_len` after initializing a `Vec` in `Exportable` - this small change fixes this behavior
> Fix `Exportable` for `Vec<T>`

- src/Cryptol/Eval/Concrete.hs
Fixes #1891
We were missing a `EProofApp` constructor when making numeric literals
> Fix conversion from values back to expressions

- cryptol.cabal
- src/Cryptol/Parser/AST/Builder.hs
In SAW we would like to construct Cryptol Parser AST expressions programmatically in Haskell. This module makes it more convenient than using the AST constructors directly.
> Add basic Parser AST builder API

- .github/workflows/ci.yml
A follow-up to #1897, which accidentally broke the Docker-related CI jobs. This ensures that Docker-related CI jobs always clone the `cryptol` repo before running the `.github/ci.sh` script to ensure that the script is actually available to run on a CI runner.
> CI: Ensure that Docker image jobs clone repo before running `.github/ci.sh`

- src/Cryptol/REPL/Command.hs
This PR changes how errors produced when parsing cryptol commands are handled. Instead of showing unhelpful messages like `Parse error at <interactive>:8:0, unexpected: end of file`, this PR prints the command help message and its expected arg type. 
This closes issue #1877
> Better Error Messages

- src/Cryptol/ModuleSystem/Env.hs
Don't use `ifNominalTypes (ifDefines i) <> ifNominalTypes (ifDefines i)`, as this unions together identical maps and returns the same map as if you'd just used `ifNominalTypes (ifDefines i)` directly.
Fixes https://github.com/GaloisInc/cryptol/issues/1913.
> `Cryptol.ModuleSystem.Env`: Eliminate wasted work in `loadedNominalTypes` 
