GaloisInc/cryptol

README.md
This is a trivial change to `README.md`, which only fixes tiny issues that irked me when reading through.
=> README.md: Trivial fixes

cryptol.cabal, src/Cryptol/REPL/Command.hs, src/Cryptol/Symbolic.hs, src/Cryptol/Symbolic/Value.hs
Also, bumped up the version to 2.4.1
=> Modifications to make cryptol compile with SBV 7.0

README.md
=> updated mailing list in readme

lib/Cryptol.cry
=> Update doc-strings for Cryptol prelude arithmetic operators.

src/Cryptol/ModuleSystem/Renamer.hs, src/Cryptol/Parser.y, src/Cryptol/Parser/AST.hs, src/Cryptol/Parser/Names.hs, src/Cryptol/Parser/ParserUtils.hs, src/Cryptol/TypeCheck/Kind.hs
Some simplifications and refactorings of parser/renamer code.
=> Simplify parser

lib/Cryptol.cry, src/Cryptol/ModuleSystem/NamingEnv.hs, src/Cryptol/ModuleSystem/Renamer.hs, src/Cryptol/Parser.y, src/Cryptol/Parser/AST.hs, src/Cryptol/Parser/Names.hs, src/Cryptol/Parser/NoPat.hs, src/Cryptol/Parser/ParserUtils.hs, src/Cryptol/TypeCheck/Depends.hs, src/Cryptol/TypeCheck/Kind.hs, src/Cryptol/TypeCheck/Type.hs, tests/issues/T146.icry.stdout, tests/issues/issue226.icry.stdout, tests/issues/issue290v2.icry.stdout
=> Infix type synonyms

src/Cryptol/TypeCheck/InferTypes.hs, src/Cryptol/TypeCheck/Kind.hs, src/Cryptol/TypeCheck/Monad.hs, src/Cryptol/TypeCheck/Solve.hs, src/Cryptol/TypeCheck/Solver/Improve.hs, src/Cryptol/TypeCheck/Solver/Numeric.hs, src/Cryptol/TypeCheck/Solver/Numeric/Fin.hs, src/Cryptol/TypeCheck/Solver/Types.hs, src/Cryptol/TypeCheck/Subst.hs, src/Cryptol/TypeCheck/TCon.hs, src/Cryptol/TypeCheck/Type.hs, tests/issues/issue058.icry.stdout, tests/issues/issue416.icry.stdout, tests/regression/superclass.cry, tests/regression/superclass.icry, tests/regression/superclass.icry.stdout
This PR augments the Cryptol typechecker with superclass information.  Inference and typechecking should both use this information to simplify goals.
=> Superclass inference

.github/ci.sh, .github/workflows/build.yml, CHANGES.md, cryptol.cabal, src/Cryptol/REPL/Command.hs, src/Cryptol/REPL/Monad.hs, src/Cryptol/Symbolic/SBV.hs, src/Cryptol/Symbolic/What4.hs
Fix a number of minor issues with prover selection, and bring What4 mostly up to feature parity with SBV by implementing smoke tests and portfolio solving.
=> Prover improvements

src/Cryptol/Eval/What4.hs, src/Cryptol/Eval/What4/Value.hs, src/Cryptol/Symbolic/What4.hs
…tion.
We use this in the definition of `fpToRational`.  It doesn't seem like
Z3 can do much with these at the moment, but maybe in the future.
=> Add support for emitting definitional equations during symbolic execution

win32/cryptol.wxs
Don't have a windows computer to test this on, but it seems like this should do the trick.
=> Fix windows installer path

src/Cryptol/REPL/Command.hs, src/Cryptol/REPL/Monad.hs
=> Remove code related to unused `LetEnabled` option.

.github/ci.sh, .github/workflows/build.yml, Dockerfile, cabal.project, cryptol-remote-api/CHANGELOG.md, cryptol-remote-api/LICENSE, cryptol-remote-api/Setup.hs, cryptol-remote-api/cryptol-remote-api.cabal, cryptol-remote-api/cryptol-remote-api/Main.hs, cryptol-remote-api/src/CryptolServer.hs, cryptol-remote-api/src/CryptolServer/Call.hs, cryptol-remote-api/src/CryptolServer/ChangeDir.hs, cryptol-remote-api/src/CryptolServer/Data/Expression.hs, cryptol-remote-api/src/CryptolServer/Data/Type.hs, cryptol-remote-api/src/CryptolServer/EvalExpr.hs, cryptol-remote-api/src/CryptolServer/Exceptions.hs, cryptol-remote-api/src/CryptolServer/FocusedModule.hs, cryptol-remote-api/src/CryptolServer/LoadModule.hs, cryptol-remote-api/src/CryptolServer/Names.hs, cryptol-remote-api/src/CryptolServer/Sat.hs, cryptol-remote-api/src/CryptolServer/TypeCheck.hs, cryptol-remote-api/test-scripts/Foo.cry, cryptol-remote-api/test-scripts/Inst.cry, cryptol-remote-api/test-scripts/Param.cry, cryptol-remote-api/test-scripts/cryptol-api_test.py, cryptol-remote-api/test-scripts/cryptol-tests.py, cryptol-remote-api/test-scripts/test-data/M.cry, cryptol-remote-api/test/Test.hs
This commit moves the `cryptol-remote-api` package from the `argo`
repository to the `cryptol` repository.
=> Add `cryptol-remote-api`

cryptol-remote-api/src/CryptolServer/Call.hs, cryptol-remote-api/src/CryptolServer/EvalExpr.hs, cryptol-remote-api/test-scripts/Foo.cry, cryptol-remote-api/test-scripts/Id.cry, cryptol-remote-api/test-scripts/cryptol-api_test.py
Fixes https://github.com/GaloisInc/argo/issues/109
=> fix: cryptol-remote-api allow arbitrary expression as operator in call

cryptol-remote-api/src/CryptolServer/Call.hs, cryptol-remote-api/src/CryptolServer/EvalExpr.hs, cryptol-remote-api/test-scripts/Foo.cry, cryptol-remote-api/test-scripts/Id.cry, cryptol-remote-api/test-scripts/cryptol-api_test.py
Need to merge https://github.com/GaloisInc/argo/pull/111 and re-direct submodule bump to that commit first.
=> chore: bump argo submod, tests for BitVector cryptol args

.github/workflows/docker.yml, .github/workflows/nightly.yml
Tested (with push skipped) in https://github.com/GaloisInc/cryptol/runs/1401428168
=> Build and push .github/Dockerfile-remote-api to galoisinc/cryptol-remote-api

cryptol-remote-api/cryptol-eval-server/Main.hs, cryptol-remote-api/cryptol-remote-api/Main.hs, cryptol-remote-api/src/CryptolServer.hs, cryptol-remote-api/src/CryptolServer/Call.hs, cryptol-remote-api/src/CryptolServer/ChangeDir.hs, cryptol-remote-api/src/CryptolServer/EvalExpr.hs, cryptol-remote-api/src/CryptolServer/FocusedModule.hs, cryptol-remote-api/src/CryptolServer/LoadModule.hs, cryptol-remote-api/src/CryptolServer/Names.hs, cryptol-remote-api/src/CryptolServer/Options.hs, cryptol-remote-api/src/CryptolServer/Sat.hs, cryptol-remote-api/src/CryptolServer/TypeCheck.hs, cryptol-remote-api/test-scripts/cryptol-tests.py, cryptol-remote-api/test-scripts/eval-server-test.py
Submodule needs updated after https://github.com/GaloisInc/argo/pull/133 is merged - otherwise barring any test failures or similar I believe it's ready basically.
=> cryptol-remote-api: submod bump and docs

cryptol-remote-api/cryptol-eval-server/Main.hs, cryptol-remote-api/cryptol-remote-api/Main.hs, cryptol-remote-api/src/CryptolServer/Sat.hs, cryptol-remote-api/test-scripts/Foo.cry, cryptol-remote-api/test-scripts/cryptol-api_test.py
This currently depends on GaloisInc/argo#144, which we should merge first.
=> Add remote API calls for for proving properties

cryptol.cabal, src/Cryptol/Backend/Concrete.hs, src/Cryptol/Backend/FloatHelpers.hs
0.6 has some bugfixes and additional operations.
This won't be ready to merge until we get the libBF version uploaded to Hackage.
=> Update to use `libBF` version 0.6

src/Cryptol/Backend/Monad.hs, src/Cryptol/TypeCheck/Error.hs
Explain that the error might occur because of retrying an
interrupted computation and suggest that reloading might
alleviate the issue.
Fixes #1030
=> Add some text to the <<loop>> error

cryptol-remote-api/cryptol-eval-server/Main.hs, src/Cryptol/ModuleSystem/Base.hs, src/Cryptol/ModuleSystem/Monad.hs, src/Cryptol/REPL/Command.hs, src/Cryptol/TypeCheck.hs, src/Cryptol/TypeCheck/InferTypes.hs, src/Cryptol/TypeCheck/Monad.hs, src/Cryptol/TypeCheck/Solver/SMT.hs
Refactor the use of SMT solvers for typechecking to allow for the solver instances to be reused for a longer period.
=> Persist solver

src/Cryptol/TypeCheck/Error.hs, src/Cryptol/TypeCheck/Infer.hs, src/Cryptol/TypeCheck/Instantiate.hs, src/Cryptol/TypeCheck/Kind.hs, src/Cryptol/TypeCheck/Monad.hs, src/Cryptol/TypeCheck/Type.hs, tests/issues/issue1024.icry, tests/issues/issue1024.icry.stdout, tests/issues/issue1024a.cry, tests/issues/issue1024b.cry
Restrict the kinds that are allowed for most flavors of parameters.
=> Improved kind-checking for parameters

cryptol.cabal
=> Allow sbv 8.10

cryptol.cabal
=> Allow sbv 8.11

cryptol.cabal
=> Allow sbv 8.12

.github/ci.sh, .github/workflows/ci.yml
Handful of CI fixes ported from the release-2.11.0 branch.
=> Fix CI release signing and docker caching

cryptol.cabal
=> Allow sbv 8.13

cryptol.cabal
=> Allow sbv 8.14

cryptol.cabal
=> Allow sbv 8.15

src/Cryptol/ModuleSystem/Renamer.hs, tests/issues/issue1240.cry, tests/issues/issue1240.icry, tests/issues/issue1240.icry.stdout
=> The types of module parameters use constraints

src/Cryptol/Eval.hs, src/Cryptol/TypeCheck/TypeOf.hs
Adds some missing cases regarding tuple and record selectors.
=> fastTypeOf fixes

cryptol.cabal
=> Allow sbv 8.16

cryptol-remote-api/python/poetry.lock, cryptol-remote-api/python/tests/cryptol/test_CplxQNewtype.py, cryptol-remote-api/python/tests/cryptol/test_cryptol_api.py, cryptol-remote-api/python/tests/cryptol_eval/test_basics.py
~~TODO: push argo to PyPI once that's finalized, bump cryptol client to use that instead of `develop` dependency.~~
~~TODO: update any other poetry.lock etc stuff.~~
=> fix: bump argo submodule, fix unknown ID errors for RPC server

CHANGES.md, CODE_OF_CONDUCT.md, README.md
* Update `CHANGES.md`
* Include Code of Conduct
=> Prepare for 2.12 release

src/Cryptol/REPL/Command.hs, tests/modsys/T14.icry.stdout, tests/modsys/T14.icry.stdout.mingw32, tests/modsys/T16.icry.stdout, tests/modsys/T16.icry.stdout.mingw32, tests/modsys/T18.icry.stdout, tests/modsys/T18.icry.stdout.mingw32
=> Make `:module` work more like `:load`.

cryptol-remote-api/python/CHANGELOG.md, cryptol-remote-api/python/poetry.lock, cryptol-remote-api/python/pyproject.toml
See https://github.com/GaloisInc/cryptol/issues/1335
=> python client: add typing-extensions as an explicit dependency

cryptol.cabal
=> Allow sbv 8.17

src/Cryptol/Parser.y, tests/issues/issue1344.icry, tests/issues/issue1344.icry.stdout, tests/issues/issue1344/A.cry, tests/issues/issue1344/issue1344.cry
=> Allow infix operators in import lists

.github/workflows/ci.yml
=> CI: Distinguish artifact names by GHC version

tests/issues/issue835.icry, tests/issues/issue835.icry.stdout
=> Update regression test for issue #835.

docs/ffi-presentation.md
I'm not sure if this belongs here but I saw that there are some slides from @yav about the module system in the `docs` directory so I thought I'd add the slides from my presentation last Friday.
=> Add FFI presentation slides

.github/ci.sh, CHANGES.md, cryptol.cabal, docs/ProgrammingCryptol/crashCourse/CrashCourse.tex, lib/Cryptol.cry, tests/issues/issue103.icry.stdout, tests/modsys/T16.icry.stdout, tests/modsys/T16.icry.stdout.mingw32, tests/regression/safety.icry.stdout
=> Improve the documentation of `fromInteger`

.github/workflows/ci.yml
[As suggested by](https://github.com/GaloisInc/cryptol/pull/1527#discussion_r1225129937) @RyanGlScott to fix failing tests on Windows
=> CI: Use haskell/actions/setup@v2

src/Cryptol/IR/FreeVars.hs
=> Collect free variables from `Type` field of `EPropGuards` in `FreeVars Expr` instance

src/Cryptol/ModuleSystem/Env.hs, tests/issues/issue1621/a.cry, tests/issues/issue1621/b.cry, tests/issues/issue1621/issue1621.icry, tests/issues/issue1621/issue1621.icry.stdout
#1621
Make it so only public IfaceDecls are loaded from other modules
=> Make it so only public IfaceDecls are loaded from other modules

src/Cryptol/TypeCheck/Solver/SMT.hs
=> Export `push` and `pop`

src/Cryptol/Utils/PP.hs
Fix pretty printing of PrimIdent
=> Fixes #1672

lib/Cryptol.cry, tests/ffi/ffi-runtime-errors.icry.stdout, tests/ffi/ffi-runtime-errors.icry.stdout.darwin, tests/ffi/ffi-runtime-errors.icry.stdout.mingw32, tests/ffi/ffi-type-errors.icry.stdout, tests/issues/T146.icry.stdout, tests/issues/issue1024.icry.stdout, tests/issues/issue290v2.icry.stdout, tests/issues/issue723.icry.stdout, tests/regression/tc-errors.icry.stdout
Remove defaulting warning in the Prelude
=> Fixes #1490

src/Cryptol/TypeCheck/Module.hs, src/Cryptol/TypeCheck/Monad.hs, tests/docstrings/T06.cry, tests/docstrings/T06.icry, tests/docstrings/T06.icry.stdout
=> Propagate nested relation when instantiating functors

src/Cryptol/Parser.y, src/Cryptol/Parser/ParserUtils.hs, tests/docstrings/T12.cry, tests/docstrings/T12.icry, tests/docstrings/T12.icry.stdout
=> Allow doc comments on interface modules

CHANGES.md, src/Cryptol/Parser/AST.hs, src/Cryptol/TypeCheck/Error.hs, src/Cryptol/TypeCheck/Infer.hs, src/Cryptol/TypeCheck/Monad.hs, tests/constraint-guards/constant.icry.stdout, tests/constraint-guards/nestMod.icry.stdout, tests/issues/issue1798.cry, tests/issues/issue1798.icry, tests/issues/issue1798.icry.stdout
also order warning output based on source location
fixes #1798
=> add source spans to exhaustivity warnings

docs/Syntax.md, src/Cryptol/Backend/Monad.hs, src/Cryptol/ModuleSystem/Env.hs, src/Cryptol/ModuleSystem/Interface.hs, src/Cryptol/ModuleSystem/NamingEnv.hs, tests/issues/issue211.icry.stdout
- minor tweaks, comments, but importantly ...
- refactorings and new function to support sawscript issue: 1964 "allow importing cryptol submodules into saw"
=> Wibbles and Refactorings to support submodules in SAWScript.

cryptol-remote-api/src/CryptolServer/CheckDocstrings.hs, cryptol-remote-api/src/CryptolServer/Sat.hs, cryptol-repl-internal/REPL/Haskeline.hs, src/Cryptol/Eval/Type.hs, src/Cryptol/REPL/Browse.hs, src/Cryptol/REPL/Command.hs, src/Cryptol/REPL/Monad.hs, src/Cryptol/Symbolic.hs, src/Cryptol/Symbolic/SBV.hs, src/Cryptol/Symbolic/What4.hs, src/Cryptol/Utils/PP.hs
Better error message when the type of `:prove` is not supported.  Fixes #1906. Fixes #1907
=> Add support for annotations while pretty printing
